

INSERT INTO FORM_TEMPLATE(ID,TYPE,NAME,CONTENT) VALUES(1,0,'申请单','{"title":"申请单","template":"oneColumn","fields":[{"type":"textfield","id":"_xf_1","name":"reason","label":"请假原因","data":"","row":0,"col":0},{"type":"radio","id":"_xf_2","name":"type","label":"请假类型","data":"倒休,事假,病假,婚假","row":1,"col":0}],"buttons":["保存","提交"]}');

INSERT INTO FORM_TEMPLATE(ID,TYPE,NAME,CONTENT) VALUES(2,0,'上级审批','{"title":"上级审批","template":"oneColumn","fields":[{"type":"textfield","id":"_xf_1","name":"reason","label":"请假原因","data":"","row":0,"col":0,"readOnly":true},{"type":"radio","id":"_xf_2","name":"type","label":"请假类型","data":"倒休,事假,病假,婚假","row":1,"col":0,"readOnly":true},{"type":"radio","id":"_xf_3","name":"leaderComment","label":"部门经理意见","data":"同意,不同意","row":2,"col":0}],"buttons":["保存","提交"]}');

INSERT INTO FORM_TEMPLATE(ID,TYPE,NAME,CONTENT) VALUES(3,0,'人事审批','{"title":"人事审批","template":"oneColumn","fields":[{"type":"textfield","id":"_xf_1","name":"reason","label":"请假原因","data":"","row":0,"col":0,"readOnly":true},{"type":"radio","id":"_xf_2","name":"type","label":"请假类型","data":"倒休,事假,病假,婚假","row":1,"col":0,"readOnly":true},{"type":"radio","id":"_xf_3","name":"leaderComment","label":"部门经理意见","data":"同意,不同意","row":2,"col":0,"readOnly":true},{"type":"radio","id":"_xf_4","name":"hrComment","label":"人事意见","data":"同意,不同意","row":3,"col":0}],"buttons":["保存","提交"]}');

INSERT INTO FORM_TEMPLATE(ID,TYPE,NAME,CONTENT) VALUES(4,0,'调整申请','{"title":"调整申请","template":"oneColumn","fields":[{"type":"textfield","id":"_xf_1","name":"reason","label":"请假原因","data":"","row":0,"col":0},{"type":"radio","id":"_xf_2","name":"type","label":"请假类型","data":"倒休,事假,病假,婚假","row":1,"col":0},{"type":"radio","id":"_xf_3","name":"initiatorComment","label":"调整申请","data":"重新申请,撤销申请","row":2,"col":0}],"buttons":["保存","提交"]}');

INSERT INTO FORM_TEMPLATE(ID,TYPE,NAME,CONTENT) VALUES(5,0,'销假','{"title":"销假","template":"oneColumn","fields":[{"type":"textfield","id":"_xf_1","name":"reason","label":"请假原因","data":"","row":0,"col":0,"readOnly":true},{"type":"radio","id":"_xf_2","name":"type","label":"请假类型","data":"倒休,事假,病假,婚假","row":1,"col":0,"readOnly":true},{"type":"radio","id":"_xf_3","name":"leaderComment","label":"部门经理意见","data":"同意,不同意","row":2,"col":0,"readOnly":true},{"type":"radio","id":"_xf_4","name":"hrComment","label":"人事意见","data":"同意,不同意","row":3,"col":0,"readOnly":true}],"buttons":["保存","提交"]}');

INSERT INTO FORM_TEMPLATE(ID,TYPE,NAME,CONTENT) VALUES(6,0,'发文','{"title":"发文","template":"oneColumn","fields":[{"type":"textfield","id":"_xf_1","name":"title","label":"标题","data":"","row":0,"col":0},{"type":"userPicker","id":"_xf_2","name":"countersignUsers","label":"拟稿审批","data":"","row":1,"col":0},{"type":"textarea","id":"_xf_3","name":"content","label":"内容","data":"","row":2,"col":0}],"buttons":["保存","提交"]}');

INSERT INTO FORM_TEMPLATE(ID,TYPE,NAME,CONTENT) VALUES(7,0,'经理审批','{"title":"经理审批","template":"oneColumn","fields":[{"type":"textfield","id":"_xf_1","name":"title","label":"标题","data":"","row":0,"col":0,"readOnly":true},{"type":"textarea","id":"_xf_2","name":"content","label":"内容","data":"","row":1,"col":0,"readOnly":true},{"type":"radio","id":"_xf_3","name":"leaderComment","label":"部门经理意见","data":"同意,不同意","row":2,"col":0}],"buttons":["保存","提交"]}');

INSERT INTO FORM_TEMPLATE(ID,TYPE,NAME,CONTENT) VALUES(8,0,'会签审批','{"title":"会签审批","template":"oneColumn","fields":[{"type":"textfield","id":"_xf_1","name":"title","label":"标题","data":"","row":0,"col":0,"readOnly":true},{"type":"textarea","id":"_xf_2","name":"content","label":"内容","data":"","row":1,"col":0,"readOnly":true},{"type":"radio","id":"_xf_3","name":"leaderComment","label":"部门经理意见","data":"同意,不同意","row":2,"col":0,"readOnly":true},{"type":"radio","id":"_xf_4","name":"countersignComment","label":"审批意见","data":"同意,不同意","row":2,"col":0}],"buttons":["保存","提交"]}');

INSERT INTO FORM_TEMPLATE(ID,TYPE,NAME,CONTENT) VALUES(9,0,'归档','{"title":"归档","template":"oneColumn","fields":[{"type":"textfield","id":"_xf_1","name":"title","label":"标题","data":"","row":0,"col":0,"readOnly":true},{"type":"textarea","id":"_xf_2","name":"content","label":"内容","data":"","row":1,"col":0,"readOnly":true}],"buttons":["保存","提交"]}');

INSERT INTO FORM_TEMPLATE(ID,TYPE,NAME,CONTENT) VALUES(10,0,'permission发起申请','{"title":"发起申请","template":"oneColumn","fields":[{"type":"textfield","id":"_xf_1","name":"name","label":"申请","data":"","row":0,"col":0}],"buttons":["保存","提交"]}');

INSERT INTO FORM_TEMPLATE(ID,TYPE,NAME,CONTENT) VALUES(11,0,'permission经理审批','{"title":"经理审批","template":"oneColumn","fields":[{"type":"textfield","id":"_xf_1","name":"name","label":"申请","data":"","row":0,"col":0,"readOnly":true},{"type":"radio","id":"_xf_2","name":"managerComment","label":"经理审批意见","data":"同意,不同意","row":1,"col":0}],"buttons":["保存","提交"]}');

INSERT INTO FORM_TEMPLATE(ID,TYPE,NAME,CONTENT) VALUES(12,0,'permission模块负责人审批','{"title":"模块负责人审批","template":"oneColumn","fields":[{"type":"textfield","id":"_xf_1","name":"name","label":"申请","data":"","row":0,"col":0,"readOnly":true},{"type":"radio","id":"_xf_2","name":"managerComment","label":"经理审批意见","data":"同意,不同意","row":1,"col":0,"readOnly":true},{"type":"radio","id":"_xf_3","name":"leaderComment","label":"模块负责人审批意见","data":"同意,不同意","row":2,"col":0}],"buttons":["保存","提交"]}');

INSERT INTO FORM_TEMPLATE(ID,TYPE,NAME,CONTENT) VALUES(13,0,'permission内审审批','{"title":"内审审批","template":"oneColumn","fields":[{"type":"textfield","id":"_xf_1","name":"name","label":"申请","data":"","row":0,"col":0,"readOnly":true},{"type":"radio","id":"_xf_2","name":"managerComment","label":"经理审批意见","data":"同意,不同意","row":1,"col":0,"readOnly":true},{"type":"radio","id":"_xf_3","name":"leaderComment","label":"模块负责人审批意见","data":"同意,不同意","row":2,"col":0,"readOnly":true},{"type":"radio","id":"_xf_4","name":"oiaComment","label":"内审审批意见","data":"同意,不同意","row":3,"col":0}],"buttons":["保存","提交"]}');


UPDATE FORM_TEMPLATE SET NAME='permission总经理审批' where id=12;

DELETE FROM FORM_TEMPLATE WHERE ID=13;



UPDATE FORM_TEMPLATE SET CONTENT='{"sections":[{"type":"text","tag":"h1","text":"申请单"},{"type":"grid","row":"2","col":"4","merge":[{"startId":"0-1","minRow":0,"minCol":1,"maxRow":0,"maxCol":3},{"startId":"1-1","minRow":1,"minCol":1,"maxRow":1,"maxCol":3}],"fields":[{"type":"label","row":0,"col":0,"text":"请假原因"},{"type":"label","row":1,"col":0,"text":"请假类型"},{"type":"textfield","row":0,"col":1,"name":"reason","required":false,"readOnly":false},{"type":"radio","row":1,"col":1,"name":"type","items":"倒休,事假,病假,婚假","required":false,"readOnly":false}]}]}' where ID=1;

UPDATE FORM_TEMPLATE SET CONTENT='{"sections":[{"type":"text","tag":"h1","text":"上级审批"},{"type":"grid","row":"3","col":"4","merge":[{"startId":"0-1","minRow":0,"minCol":1,"maxRow":0,"maxCol":3},{"startId":"1-1","minRow":1,"minCol":1,"maxRow":1,"maxCol":3},{"startId":"2-1","minRow":2,"minCol":1,"maxRow":2,"maxCol":3}],"fields":[{"type":"label","row":0,"col":0,"text":"请假原因"},{"type":"label","row":1,"col":0,"text":"请假类型"},{"type":"textfield","row":0,"col":1,"name":"reason","required":false,"readOnly":true},{"type":"radio","row":1,"col":1,"name":"type","items":"倒休,事假,病假,婚假","required":false,"readOnly":true},{"type":"label","row":2,"col":0,"text":"部门经理意见"},{"type":"radio","row":2,"col":1,"name":"leaderComment","items":"同意,不同意","required":false,"readOnly":false}]}]}' where ID=2;

UPDATE FORM_TEMPLATE SET CONTENT='{"sections":[{"type":"text","tag":"h1","text":"人事审批"},{"type":"grid","row":"4","col":"4","merge":[{"startId":"0-1","minRow":0,"minCol":1,"maxRow":0,"maxCol":3},{"startId":"1-1","minRow":1,"minCol":1,"maxRow":1,"maxCol":3},{"startId":"2-1","minRow":2,"minCol":1,"maxRow":2,"maxCol":3},{"startId":"3-1","minRow":3,"minCol":1,"maxRow":3,"maxCol":3}],"fields":[{"type":"label","row":0,"col":0,"text":"请假原因"},{"type":"label","row":1,"col":0,"text":"请假类型"},{"type":"textfield","row":0,"col":1,"name":"reason","required":false,"readOnly":true},{"type":"radio","row":1,"col":1,"name":"type","items":"倒休,事假,病假,婚假","required":false,"readOnly":true},{"type":"label","row":2,"col":0,"text":"部门经理意见"},{"type":"radio","row":2,"col":1,"name":"leaderComment","items":"同意,不同意","required":false,"readOnly":true},{"type":"label","row":3,"col":0,"text":"人事意见"},{"type":"radio","row":3,"col":1,"name":"hrComment","items":"同意,不同意","required":false,"readOnly":false}]}]}' where ID=3;

UPDATE FORM_TEMPLATE SET CONTENT='{"sections":[{"type":"text","tag":"h1","text":"调整申请"},{"type":"grid","row":"3","col":"4","merge":[{"startId":"0-1","minRow":0,"minCol":1,"maxRow":0,"maxCol":3},{"startId":"1-1","minRow":1,"minCol":1,"maxRow":1,"maxCol":3},{"startId":"2-1","minRow":2,"minCol":1,"maxRow":2,"maxCol":3},{"startId":"3-1","minRow":3,"minCol":1,"maxRow":3,"maxCol":3}],"fields":[{"type":"label","row":0,"col":0,"text":"请假原因"},{"type":"label","row":1,"col":0,"text":"请假类型"},{"type":"textfield","row":0,"col":1,"name":"reason","required":false,"readOnly":false},{"type":"radio","row":1,"col":1,"name":"type","items":"倒休,事假,病假,婚假","required":false,"readOnly":false},{"type":"label","row":2,"col":0,"text":"调整申请"},{"type":"radio","row":2,"col":1,"name":"initiatorComment","items":"重新申请,撤销申请","required":false,"readOnly":false}]}]}' where ID=4;

UPDATE FORM_TEMPLATE SET CONTENT='{"sections":[{"type":"text","tag":"h1","text":"人事审批"},{"type":"grid","row":"4","col":"4","merge":[{"startId":"0-1","minRow":0,"minCol":1,"maxRow":0,"maxCol":3},{"startId":"1-1","minRow":1,"minCol":1,"maxRow":1,"maxCol":3},{"startId":"2-1","minRow":2,"minCol":1,"maxRow":2,"maxCol":3},{"startId":"3-1","minRow":3,"minCol":1,"maxRow":3,"maxCol":3}],"fields":[{"type":"label","row":0,"col":0,"text":"请假原因"},{"type":"label","row":1,"col":0,"text":"请假类型"},{"type":"textfield","row":0,"col":1,"name":"reason","required":false,"readOnly":true},{"type":"radio","row":1,"col":1,"name":"type","items":"倒休,事假,病假,婚假","required":false,"readOnly":true},{"type":"label","row":2,"col":0,"text":"部门经理意见"},{"type":"radio","row":2,"col":1,"name":"leaderComment","items":"同意,不同意","required":false,"readOnly":true},{"type":"label","row":3,"col":0,"text":"人事意见"},{"type":"radio","row":3,"col":1,"name":"hrComment","items":"同意,不同意","required":false,"readOnly":true}]}]}' where ID=5;

UPDATE FORM_TEMPLATE SET CONTENT='{"sections":[{"type":"text","tag":"h1","text":"发文"},{"type":"grid","row":"3","col":"4","merge":[{"startId":"0-1","minRow":0,"minCol":1,"maxRow":0,"maxCol":3},{"startId":"1-1","minRow":1,"minCol":1,"maxRow":1,"maxCol":3},{"startId":"2-1","minRow":2,"minCol":1,"maxRow":2,"maxCol":3}],"fields":[{"type":"label","row":0,"col":0,"text":"标题"},{"type":"textfield","row":0,"col":1,"name":"title","required":false,"readOnly":false},{"type":"textarea","row":2,"col":1,"name":"content","required":false,"readOnly":false},{"type":"label","row":2,"col":0,"text":"内容"},{"type":"label","row":1,"col":0,"text":"拟稿审批"},{"type":"userpicker","row":1,"col":1,"name":"countersignUsers","required":false,"readOnly":false}]}]}' where ID=6;

UPDATE FORM_TEMPLATE SET CONTENT='{"sections":[{"type":"text","tag":"h1","text":"经理审批"},{"type":"grid","row":"3","col":"4","merge":[{"startId":"0-1","minRow":0,"minCol":1,"maxRow":0,"maxCol":3},{"startId":"1-1","minRow":1,"minCol":1,"maxRow":1,"maxCol":3},{"startId":"2-1","minRow":2,"minCol":1,"maxRow":2,"maxCol":3}],"fields":[{"type":"label","row":0,"col":0,"text":"标题"},{"type":"textfield","row":0,"col":1,"name":"title","required":false,"readOnly":true},{"type":"radio","row":2,"col":1,"name":"leaderComment","items":"同意,不同意","required":false,"readOnly":false},{"type":"label","row":2,"col":0,"text":"部门经理意见"},{"type":"label","row":1,"col":0,"text":"内容"},{"type":"textarea","row":1,"col":1,"name":"content","required":false,"readOnly":true}]}]}' where ID=7;

UPDATE FORM_TEMPLATE SET CONTENT='{"sections":[{"type":"text","tag":"h1","text":"会签审批"},{"type":"grid","row":"3","col":"4","merge":[{"startId":"0-1","minRow":0,"minCol":1,"maxRow":0,"maxCol":3},{"startId":"1-1","minRow":1,"minCol":1,"maxRow":1,"maxCol":3},{"startId":"2-1","minRow":2,"minCol":1,"maxRow":2,"maxCol":3}],"fields":[{"type":"label","row":0,"col":0,"text":"标题"},{"type":"textfield","row":0,"col":1,"name":"title","required":false,"readOnly":true},{"type":"radio","row":2,"col":1,"name":"countersignComment","items":"同意,不同意","required":false,"readOnly":false},{"type":"label","row":2,"col":0,"text":"审批意见"},{"type":"label","row":1,"col":0,"text":"内容"},{"type":"textarea","row":1,"col":1,"name":"content","required":false,"readOnly":true}]}]}' where ID=8;

UPDATE FORM_TEMPLATE SET CONTENT='{"sections":[{"type":"text","tag":"h1","text":"归档"},{"type":"grid","row":"2","col":"4","merge":[{"startId":"0-1","minRow":0,"minCol":1,"maxRow":0,"maxCol":3},{"startId":"1-1","minRow":1,"minCol":1,"maxRow":1,"maxCol":3}],"fields":[{"type":"label","row":0,"col":0,"text":"标题"},{"type":"textfield","row":0,"col":1,"name":"title","required":false,"readOnly":true},{"type":"textarea","row":1,"col":1,"name":"content","required":false,"readOnly":true},{"type":"label","row":1,"col":0,"text":"内容"}]}]}' where ID=9;

UPDATE FORM_TEMPLATE SET CONTENT='{"sections":[{"type":"text","tag":"h1","text":"permission发起申请"},{"type":"grid","row":"1","col":"4","merge":[{"startId":"0-1","minRow":0,"minCol":1,"maxRow":0,"maxCol":3}],"fields":[{"type":"label","row":0,"col":0,"text":"申请"},{"type":"textfield","row":0,"col":1,"name":"name","required":false,"readOnly":false}]}]}' where ID=10;

UPDATE FORM_TEMPLATE SET CONTENT='{"sections":[{"type":"text","tag":"h1","text":"permission经理审批"},{"type":"grid","row":"2","col":"4","merge":[{"startId":"0-1","minRow":0,"minCol":1,"maxRow":0,"maxCol":3},{"startId":"1-1","minRow":1,"minCol":1,"maxRow":1,"maxCol":3}],"fields":[{"type":"label","row":0,"col":0,"text":"申请"},{"type":"textfield","row":0,"col":1,"name":"name","required":false,"readOnly":true},{"type":"label","row":1,"col":0,"text":"经理审批意见"},{"type":"radio","row":1,"col":1,"name":"managerComment","items":"同意,不同意","required":false,"readOnly":false}]}]}' where ID=11;

UPDATE FORM_TEMPLATE SET CONTENT='{"sections":[{"type":"text","tag":"h1","text":"permission模块负责人审批"},{"type":"grid","row":"3","col":"4","merge":[{"startId":"0-1","minRow":0,"minCol":1,"maxRow":0,"maxCol":3},{"startId":"1-1","minRow":1,"minCol":1,"maxRow":1,"maxCol":3},{"startId":"2-1","minRow":2,"minCol":1,"maxRow":2,"maxCol":3}],"fields":[{"type":"label","row":0,"col":0,"text":"申请"},{"type":"textfield","row":0,"col":1,"name":"name","required":false,"readOnly":true},{"type":"label","row":1,"col":0,"text":"经理审批意见"},{"type":"radio","row":1,"col":1,"name":"managerComment","items":"同意,不同意","required":false,"readOnly":true},{"type":"label","row":2,"col":0,"text":"模块负责人审批意见"},{"type":"radio","row":2,"col":1,"name":"leaderComment","items":"同意,不同意","required":false,"readOnly":false}]}]}' where ID=12;

