
CREATE TABLE PARTY_STRUCT_RULE(
        ID BIGINT auto_increment,
        STRUCT_TYPE_ID BIGINT NOT NULL,
        PARENT_TYPE_ID BIGINT NULL,
		CHILD_TYPE_ID BIGINT NOT NULL,
		SCOPE_ID VARCHAR(50),
		CONSTRAINT PK_PARTY_STRUCT_RULE PRIMARY KEY(ID)
) engine=innodb;

ALTER TABLE PARTY_STRUCT_RULE ADD FOREIGN KEY FK_PARTY_STRUCT_RULE_TYPE(STRUCT_TYPE_ID) REFERENCES PARTY_STRUCT_TYPE(ID);
ALTER TABLE PARTY_STRUCT_RULE ADD FOREIGN KEY FK_PARTY_STRUCT_RULE_TYPE_PARENT(PARENT_TYPE_ID) REFERENCES PARTY_TYPE(ID);
ALTER TABLE PARTY_STRUCT_RULE ADD FOREIGN KEY FK_PARTY_STRUCT_RULE_TYPE_CHILD(CHILD_TYPE_ID) REFERENCES PARTY_TYPE(ID);

