INSERT INTO IB_COMPANY(ID,NAME,STATUS,SCOPE_ID) VALUES(1,'天翔软件有限公司',1,'1');

INSERT INTO IB_DEPARTMENT(ID,NAME,COMPANYID,STATUS,SCOPE_ID) VALUES(1,'市场部',1,1,'1');
INSERT INTO IB_DEPARTMENT(ID,NAME,COMPANYID,STATUS,SCOPE_ID) VALUES(2,'财务部',1,1,'1');
INSERT INTO IB_DEPARTMENT(ID,NAME,COMPANYID,STATUS,SCOPE_ID) VALUES(3,'人事部',1,1,'1');
INSERT INTO IB_DEPARTMENT(ID,NAME,COMPANYID,STATUS,SCOPE_ID) VALUES(4,'研发部',1,1,'1');

INSERT INTO IB_GROUP(ID,NAME,COMPANYID,DEPTID,STATUS,SCOPE_ID) VALUES(1,'平台组',1,1,1,'1');
INSERT INTO IB_GROUP(ID,NAME,COMPANYID,DEPTID,STATUS,SCOPE_ID) VALUES(2,'OA组',1,2,1,'1');

