
CREATE TABLE PARTY_STRUCT_RULE(
        ID BIGINT PRIMARY KEY auto_increment,
        STRUCT_TYPE_ID BIGINT NOT NULL,
        PARENT_TYPE_ID BIGINT NULL,
		CHILD_TYPE_ID BIGINT NOT NULL,
		SCOPE_ID VARCHAR(50),
        CONSTRAINT FK_PARTY_STRUCT_RULE_TYPE(STRUCT_TYPE_ID) REFERENCES PARTY_STRUCT_TYPE(ID),
        CONSTRAINT FK_PARTY_STRUCT_RULE_TYPE_PARENT(PARENT_TYPE_ID) REFERENCES PARTY_TYPE(ID),
        CONSTRAINT FK_PARTY_STRUCT_RULE_TYPE_CHILD(CHILD_TYPE_ID) REFERENCES PARTY_TYPE(ID)
) engine=innodb;
