
CREATE TABLE PARTY_STRUCT_TYPE(
        ID BIGINT auto_increment,
        NAME VARCHAR(50),
		REF VARCHAR(50),
		SCOPE_ID VARCHAR(50),
		PRIORITY INT,
        CONSTRAINT PK_PARTY_STRUCT_TYPE PRIMARY KEY(ID)
) engine=innodb;
