
CREATE TABLE PARTY_STRUCT(
        ID BIGINT PRIMARY KEY auto_increment,
        STRUCT_TYPE_ID BIGINT NOT NULL,
        PARENT_ENTITY_ID BIGINT NULL,
        CHILD_ENTITY_ID BIGINT NOT NULL,
		PRIORITY INTEGER,
		SCOPE_ID VARCHAR(50),
        PART_TIME INT,
        LINK INT,
        ADMIN INT,
        CONSTRAINT FK_PARTY_STRUCT_TYPE FOREIGN KEY(STRUCT_TYPE_ID) REFERENCES PARTY_STRUCT_TYPE(ID),
        CONSTRAINT FK_PARTY_STRUCT_PARENT FOREIGN KEY(PARENT_ENTITY_ID) REFERENCES PARTY_ENTITY(ID),
        CONSTRAINT FK_PARTY_STRUCT_CHILD FOREIGN KEY(CHILD_ENTITY_ID) REFERENCES PARTY_ENTITY(ID)
) engine=innodb;
