/* ======================== 运行管理 ====================  */
/* ====== 空调控制记录表 =====  */
DROP TABLE IF EXISTS IB_AIRCONDITIONLOG;
CREATE TABLE IB_AIRCONDITIONLOG (EVENTTIME DATETIME, CONTROLUSER VARCHAR(64), CONTROLINFO VARCHAR(512), ID VARCHAR(64),  PRIMARY KEY (ID)) ENGINE=INNODB;
