/* ======================== 业务模块组件管理表 ====================  */
/* ====== 测试练习表 =====  */
DROP TABLE IF EXISTS IB_TEST;
CREATE TABLE IB_TEST (ID VARCHAR(64), SCOPEID VARCHAR(64), NAME VARCHAR(64), REMARK VARCHAR(1024), CONSTRAINT PK_IB_TEST PRIMARY KEY(ID)) ENGINE=INNODB;
/* ====== 审批权限流程表 =====  */
DROP TABLE IF EXISTS IB_PERMISSION;
CREATE TABLE  IB_PERMISSION(ID VARCHAR(64) NOT NULL, EXECUTIONID VARCHAR(64), CREATEDATEBPM DATETIME, NODENAME VARCHAR(128), ASSIGNEEUSER VARCHAR(128), USERNAME VARCHAR(128), TASKTITLE VARCHAR(256), REMARK VARCHAR(512), DONEFLAG INT DEFAULT 0, PRIMARY KEY (ID)) ENGINE=INNODB;
/* ====== 审批权限流程子表 =====  */
DROP TABLE IF EXISTS IB_PERMISSION_S;
CREATE TABLE IB_PERMISSION_S ( ID  VARCHAR(64), PARENTID VARCHAR(64),REMARK VARCHAR(1024), CONSTRAINT PK_IB_PERMISSION_S PRIMARY KEY(ID)) ENGINE=INNODB;
