/* ======================== 运行管理 ====================  */
/* ====== 空调控制记录表 =====  */
DROP TABLE IF EXISTS IB_AIRCONDITIONLOG;
CREATE TABLE IB_AIRCONDITIONLOG (EVENTTIME DATETIME, CONTROLUSER VARCHAR(64), CONTROLINFO VARCHAR(512), ID VARCHAR(64),  PRIMARY KEY (ID)) ENGINE=INNODB;
/*======= PLC绘图页面 设备对象配置管理表 =======*/
DROP TABLE IF EXISTS IB_CONF_PLCDRAW;
CREATE TABLE IB_CONF_PLCDRAW (ID VARCHAR(64), ITEMID VARCHAR(64), ITEMNAME VARCHAR(64), ITEMTYPE VARCHAR(32), ITEMTITLE VARCHAR(32), IMGHURL VARCHAR(64), IMGVURL VARCHAR(64), REMARK VARCHAR(1024),  PRIMARY KEY (ID)) ENGINE=INNODB;
/*======= PLC弹出页面配置页面 ==========*/
DROP TABLE IF EXISTS IB_CONF_POPUP_PAGE;
CREATE TABLE IB_CONF_POPUP_PAGE (PAGENAME VARCHAR(64), PAGETITLE VARCHAR(128), POPUPTYPE VARCHAR(16), PAGEURL VARCHAR(256), PAGETYPE VARCHAR(16), MAINPAGEID VARCHAR(64), PAGEHIGHT VARCHAR(8), PAGEWIDTH VARCHAR(8), ID VARCHAR(64),  PRIMARY KEY (ID)) ENGINE=INNODB;
/*======= 弹出页面组件配置页面 ==========*/
DROP TABLE IF EXISTS IB_POP_CONF_CTRLOBJ;
CREATE TABLE IB_POP_CONF_CTRLOBJ (OBJNAME VARCHAR(64), OBJTITLE VARCHAR(64), OBJTYPE VARCHAR(16), OBJIMG VARCHAR(128), OBJIMG2 VARCHAR(128), OBJIMG3 VARCHAR(128), OBJIMG4 VARCHAR(128), ID VARCHAR(64),  PRIMARY KEY (ID)) ENGINE=INNODB;
