/* ==========================================================================================  */
/* =============================  IB_CONF_COMPONENT 业务模块组件管理表    =============================  */
/* ==========================================================================================  */
INSERT INTO IB_CONF_COMPONENT(ID,PACKAGENAME,MODULENAME,PARENTID,TYPEID) VALUES('budgetmanage0000','budgetmanage','预算管理','0','sModule');
INSERT INTO IB_CONF_COMPONENT(ID,PACKAGENAME,MODULENAME,PARENTID,TYPEID) VALUES('budgetmanage0001','budgetmanage','表存储设计器','budgetmanage0000','Table');
INSERT INTO IB_CONF_COMPONENT(ID,PACKAGENAME,MODULENAME,PARENTID,TYPEID) VALUES('budgetmanage0002','budgetmanage','表单设计器','budgetmanage0000','Form');
INSERT INTO IB_CONF_COMPONENT(ID,PACKAGENAME,MODULENAME,PARENTID,TYPEID) VALUES('budgetmanage0003','budgetmanage','流程表设计器','budgetmanage0000','BpmTable');
INSERT INTO IB_CONF_COMPONENT(ID,PACKAGENAME,MODULENAME,PARENTID,TYPEID) VALUES('budgetmanage0004','budgetmanage','流程表单设计器','budgetmanage0000','BpmForm');
INSERT INTO IB_CONF_COMPONENT(ID,PACKAGENAME,MODULENAME,PARENTID,TYPEID) VALUES('budgetmanage0005','budgetmanage','流程设计器','budgetmanage0000','Bpm');
/* ================= 菜单管理表  ==================   */
INSERT INTO IB_MENU(ID,MENUNAME,MENULEVEL,MENUURL,MENUIFRAME,MENUORDER,PARENTID) VALUES('budgetmanageOne','预算模块','1','#','URL','5','0');
INSERT INTO IB_MENU(ID,MENUNAME,MENULEVEL,MENUURL,MENUIFRAME,MENUORDER,PARENTID) VALUES('budgetmanageTwo1','年度预算 ','2','#','URL','1','budgetmanageOne');
INSERT INTO IB_MENU(ID,MENUNAME,MENULEVEL,MENUURL,MENUIFRAME,MENUORDER,PARENTID) VALUES('budgetmanageTwo2','月度预算 ','2','#','URL','2','budgetmanageOne');
INSERT INTO IB_MENU(ID,MENUNAME,MENULEVEL,MENUURL,MENUIFRAME,MENUORDER,PARENTID) VALUES('budgetmanageThree21','经营预算年度数据','3','/operatbudgetyear/operatbudgetyear-list.do','URL','1','budgetmanageTwo1');
INSERT INTO IB_MENU(ID,MENUNAME,MENULEVEL,MENUURL,MENUIFRAME,MENUORDER,PARENTID) VALUES('budgetmanageThree22','经营预算年度计划申报流程','3','/operatbudgetplan/operatbudgetplan-list.do?flowType=0&flowId=operatBudgetPlan001','URL','2','budgetmanageTwo1');
/*===============   菜单和角色模板关联表  =============================*/
INSERT INTO IB_MENU_ROLE_DEF(MENU_ID,ROLE_DEF_ID) VALUES('budgetmanageOne','2');
INSERT INTO IB_MENU_ROLE_DEF(MENU_ID,ROLE_DEF_ID) VALUES('budgetmanageTwo1','2');
INSERT INTO IB_MENU_ROLE_DEF(MENU_ID,ROLE_DEF_ID) VALUES('budgetmanageTwo2','2');
INSERT INTO IB_MENU_ROLE_DEF(MENU_ID,ROLE_DEF_ID) VALUES('budgetmanageThree21','2');
INSERT INTO IB_MENU_ROLE_DEF(MENU_ID,ROLE_DEF_ID) VALUES('budgetmanageThree22','2');

/* ================================================================================   */
/* ================================   经营预算年度数据表      =================================   */
/* ================================================================================   */
/*======= 表单 ==========*/
 insert into ib_conf_form(ID,PACKAGENAME,FORMNAME,FORMTITLE,FORMURL, ISEDIT,ISADD,ISDELETE,ISQUERY,ISEXCELEXPORT,ISIMPORTEXPORT,ISBPMFORM) values ('0e7b534c-f8c3-4569-a8b6-9739dd5fd9d0','budgetmanage','OperatBudgetYear','经营预算年度数据','/operatbudgetyear/operatbudgetyear-list.do',1,1,1,1,1,2,2);
/*======= 表单对应表 ==========*/
insert into ib_conf_form_table(PACKAGENAME,FORMNAME,TABLENAME,TABLETYPE) values ('budgetmanage','OperatBudgetYear','IB_OPERATBUDGETYEAR','main');
/*======= 表单字段 ==========*/
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','OperatBudgetYear','IB_OPERATBUDGETYEAR.PLANYEAR','经营预算年度数据表.计划年','PLANYEAR','IB_OPERATBUDGETYEAR',1,'1','','','1','1','1','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','OperatBudgetYear','IB_OPERATBUDGETYEAR.PROJECTTYPE','经营预算年度数据表.资金项目类别','PROJECTTYPE','IB_OPERATBUDGETYEAR',2,'1','null','null','1','1','2','null','null','null');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','OperatBudgetYear','IB_OPERATBUDGETYEAR.PROJECTNAME','经营预算年度数据表.项目计划名称','PROJECTNAME','IB_OPERATBUDGETYEAR',3,'1','null','null','1','1','2','null','null','null');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','OperatBudgetYear','IB_OPERATBUDGETYEAR.CHANGEPLANAM','经营预算年度数据表.变更前计划数','CHANGEPLANAM','IB_OPERATBUDGETYEAR',4,'1','null','null','1','1','2','null','null','null');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','OperatBudgetYear','IB_OPERATBUDGETYEAR.ADDPLANAMOUNT','经营预算年度数据表.项目增补变更计划数','ADDPLANAMOUNT','IB_OPERATBUDGETYEAR',5,'1','null','null','1','1','2','null','null','null');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','OperatBudgetYear','IB_OPERATBUDGETYEAR.PLANAMOUNT','经营预算年度数据表.现计划数','PLANAMOUNT','IB_OPERATBUDGETYEAR',6,'1','null','null','1','1','2','null','null','null');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','OperatBudgetYear','IB_OPERATBUDGETYEAR.YEARPLANBALANCE','经营预算年度数据表.年计划数余额','YEARPLANBALANCE','IB_OPERATBUDGETYEAR',7,'1','null','null','1','1','2','null','null','null');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','OperatBudgetYear','IB_OPERATBUDGETYEAR.AMOUNT','经营预算年度数据表.实际发生数','AMOUNT','IB_OPERATBUDGETYEAR',8,'1','null','null','1','1','2','null','null','null');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','OperatBudgetYear','IB_OPERATBUDGETYEAR.DEPT','经营预算年度数据表.所属部门','DEPT','IB_OPERATBUDGETYEAR',9,'1','null','null','1','1','2','null','null','null');
/*======= 表 ==========*/
insert into ib_conf_table(ID,PACKAGENAME,TABLENAME,TABLENAMECOMMENT,TABLETYPE, PARENTTABLEID,ISBPMTABLE) values ('ib_operatbudgetyear001','budgetmanage','IB_OPERATBUDGETYEAR','经营预算年度数据表','1','null',2);
/*======= 表字段 ==========*/
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETYEAR','PLANYEAR','计划年','VARCHAR','32','是','',1);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETYEAR','PROJECTTYPE','资金项目类别','VARCHAR','128','是','',2);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETYEAR','PROJECTNAME','项目计划名称','VARCHAR','256','是','',3);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETYEAR','CHANGEPLANAM','变更前计划数','NUMBER','12,2','是','',4);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETYEAR','ADDPLANAMOUNT','项目增补变更计划数','NUMBER','12,2','是','',5);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETYEAR','PLANAMOUNT','现计划数','NUMBER','12,2','是','',6);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETYEAR','YEARPLANBALANCE','年计划数余额','NUMBER','12,2','是','',7);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETYEAR','AMOUNT','实际发生数','NUMBER','12,2','是','',8);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETYEAR','DEPT','所属部门','VARCHAR','128','是','',9);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETYEAR','ID','UUID主键','VARCHAR','64','否','null',91);

/* ================================================================================   */
/* ================================   经营预算年度计划申报流程      =================================   */
/* ================================================================================   */
/*======= 流程 ==========*/
INSERT INTO IB_BPM_PROCESS(ID,PACKAGENAME,FLOWNAME,FLOWTITLE,VERSIONID, FORMID,FLOWURL) VALUES('operatBudgetPlan001','budgetmanage','operatBudgetPlan','经营预算年度计划申报流程','4371a746-b0bb-4b28-849d-b6bc552c2516','af21e2bf-3730-4fc8-af09-b91acba146d7','/operatbudgetplan/operatbudgetplan-list.do?flowType=0&flowId=operatBudgetPlan001');
/*======= 流程图 ==========*/
insert into ib_conf_flow_chart(ID,FLOWID,ITEMID,NODEID,CONTEXT) values ('0501c8f9-f5b3-4806-883f-9e80c3382839','operatBudgetPlan001','f0710dd7-9901-48b7-8918-303f5596f99b','null','{"id":"f0710dd7-9901-48b7-8918-303f5596f99b","name":"计划员确认","type":"TaskNode","title":"计划员确认","x":"800","y":"395","width":"100","height":"50","headLineIds":"2d36317f-96cf-451c-9261-0cf1cdf9713a","afterLineIds":"c0c60d23-f875-4835-aca5-b6bcdcc375ac"}');
insert into ib_conf_flow_chart(ID,FLOWID,ITEMID,NODEID,CONTEXT) values ('40bbb107-fbb7-42fc-99b6-83b4abe61dc0','operatBudgetPlan001','e388ff26-8ddd-4c2b-87cc-e994e1966a6c','null','{"id":"e388ff26-8ddd-4c2b-87cc-e994e1966a6c","name":"泳道","type":"Lane","title":"计划员确认","x":"0","y":"370","width":"35","height":"110"}');
insert into ib_conf_flow_chart(ID,FLOWID,ITEMID,NODEID,CONTEXT) values ('4366812d-4126-4ab4-b298-d67e928f9cd9','operatBudgetPlan001','2cc8af70-cd65-438d-96ac-a5f3f437d197','null','{"id":"2cc8af70-cd65-438d-96ac-a5f3f437d197","name":"线","type":"Line","title":"部门经理","x":"0","y":"150","realPoints":"250,115,250,200,400,200","startElmId":"d1ffea25-f486-470b-bcfe-124f84b2fc85","endElmId":"5dcca084-43f4-42ff-a820-4163979e281e"}');
insert into ib_conf_flow_chart(ID,FLOWID,ITEMID,NODEID,CONTEXT) values ('5a200b95-8356-4150-8df3-0cd3f4bb6200','operatBudgetPlan001','68b3f778-7d52-40ce-89ca-f60a192c3e40','null','{"id":"68b3f778-7d52-40ce-89ca-f60a192c3e40","name":"泳道","type":"Lane","title":"发起","x":"0","y":"40","width":"35","height":"110"}');
insert into ib_conf_flow_chart(ID,FLOWID,ITEMID,NODEID,CONTEXT) values ('67108baa-d017-4f15-bfa5-944b7dfbd655','operatBudgetPlan001','d1ffea25-f486-470b-bcfe-124f84b2fc85','null','{"id":"d1ffea25-f486-470b-bcfe-124f84b2fc85","name":"发起","type":"TaskNode","title":"发起","x":"200","y":"65","width":"100","height":"50","headLineIds":"81911031-9097-48b1-8890-aad7e1242888","afterLineIds":"2cc8af70-cd65-438d-96ac-a5f3f437d197"}');
insert into ib_conf_flow_chart(ID,FLOWID,ITEMID,NODEID,CONTEXT) values ('81c4f717-6d8d-44ba-830b-4c30bf201dc1','operatBudgetPlan001','42cac0a1-bf12-4353-9659-e2127858975e','null','{"id":"42cac0a1-bf12-4353-9659-e2127858975e","name":"泳道","type":"Lane","title":"部门经理","x":"0","y":"150","width":"35","height":"110"}');
insert into ib_conf_flow_chart(ID,FLOWID,ITEMID,NODEID,CONTEXT) values ('8b8cdd1b-c12e-4784-9191-0fef626c3cbf','operatBudgetPlan001','8d7d9bf9-11ae-4b5e-9e07-08390f32757b','null','{"id":"8d7d9bf9-11ae-4b5e-9e07-08390f32757b","name":"线","type":"Line","title":"总经理","x":"0","y":"260","realPoints":"450,225,450,310,600,310","startElmId":"5dcca084-43f4-42ff-a820-4163979e281e","endElmId":"639e5b7e-e870-4dc8-a6b6-7252b007a2aa"}');
insert into ib_conf_flow_chart(ID,FLOWID,ITEMID,NODEID,CONTEXT) values ('a088348e-bcf1-4f8d-b238-73f73d6c906c','operatBudgetPlan001','c0c60d23-f875-4835-aca5-b6bcdcc375ac','null','{"id":"c0c60d23-f875-4835-aca5-b6bcdcc375ac","name":"线","type":"Line","title":"计划员确认","x":"0","y":"370","realPoints":"900,420,950,420,950,420","startElmId":"f0710dd7-9901-48b7-8918-303f5596f99b","endElmId":"369d9d47-9ea3-4c7e-b41f-1182a682455c"}');
insert into ib_conf_flow_chart(ID,FLOWID,ITEMID,NODEID,CONTEXT) values ('a26aa5ce-d7bb-4a47-b6dd-29b0a654d89e','operatBudgetPlan001','3816d635-56f4-47fb-a76a-7099e000397b','null','{"id":"3816d635-56f4-47fb-a76a-7099e000397b","name":"泳道","type":"Lane","title":"总经理","x":"0","y":"260","width":"35","height":"110"}');
insert into ib_conf_flow_chart(ID,FLOWID,ITEMID,NODEID,CONTEXT) values ('a30cfa2d-03c9-4642-89da-0f8dfa00d540','operatBudgetPlan001','639e5b7e-e870-4dc8-a6b6-7252b007a2aa','null','{"id":"639e5b7e-e870-4dc8-a6b6-7252b007a2aa","name":"总经理","type":"TaskNode","title":"总经理","x":"600","y":"285","width":"100","height":"50","headLineIds":"8d7d9bf9-11ae-4b5e-9e07-08390f32757b","afterLineIds":"2d36317f-96cf-451c-9261-0cf1cdf9713a"}');
insert into ib_conf_flow_chart(ID,FLOWID,ITEMID,NODEID,CONTEXT) values ('b17e3497-ece8-478a-83a1-386cc84d0439','operatBudgetPlan001','369d9d47-9ea3-4c7e-b41f-1182a682455c','null','{"id":"369d9d47-9ea3-4c7e-b41f-1182a682455c","name":"结束节点","type":"EndNode","title":"结束","x":"950","y":"395","width":"50","height":"50","headLineIds":"c0c60d23-f875-4835-aca5-b6bcdcc375ac"}');
insert into ib_conf_flow_chart(ID,FLOWID,ITEMID,NODEID,CONTEXT) values ('c4a28030-9c3e-45b6-a4ba-3a10cbe6f887','operatBudgetPlan001','5dcca084-43f4-42ff-a820-4163979e281e','null','{"id":"5dcca084-43f4-42ff-a820-4163979e281e","name":"部门经理","type":"TaskNode","title":"部门经理","x":"400","y":"175","width":"100","height":"50","headLineIds":"2cc8af70-cd65-438d-96ac-a5f3f437d197","afterLineIds":"8d7d9bf9-11ae-4b5e-9e07-08390f32757b"}');
insert into ib_conf_flow_chart(ID,FLOWID,ITEMID,NODEID,CONTEXT) values ('d82b2126-1b98-41f1-8109-4960e9b042c5','operatBudgetPlan001','f5283262-d8cd-454b-9d0f-13e95914c302','null','{"id":"f5283262-d8cd-454b-9d0f-13e95914c302","name":"开始节点","type":"StartNode","title":"开始节点","x":"70","y":"65","width":"50","height":"50","afterLineIds":"81911031-9097-48b1-8890-aad7e1242888"}');
insert into ib_conf_flow_chart(ID,FLOWID,ITEMID,NODEID,CONTEXT) values ('efdb3129-f9de-4646-a8b8-5bd18a959128','operatBudgetPlan001','81911031-9097-48b1-8890-aad7e1242888','null','{"id":"81911031-9097-48b1-8890-aad7e1242888","name":"线","type":"Line","title":"发起","x":"0","y":"40","realPoints":"120,90,200,90","startElmId":"f5283262-d8cd-454b-9d0f-13e95914c302","endElmId":"d1ffea25-f486-470b-bcfe-124f84b2fc85"}');
insert into ib_conf_flow_chart(ID,FLOWID,ITEMID,NODEID,CONTEXT) values ('fd6afd8e-3eca-44cd-b5ec-a356be6edb31','operatBudgetPlan001','2d36317f-96cf-451c-9261-0cf1cdf9713a','null','{"id":"2d36317f-96cf-451c-9261-0cf1cdf9713a","name":"线","type":"Line","title":"计划员确认","x":"0","y":"370","realPoints":"650,335,650,420,800,420","startElmId":"639e5b7e-e870-4dc8-a6b6-7252b007a2aa","endElmId":"f0710dd7-9901-48b7-8918-303f5596f99b"}');
/*======= 表单 ==========*/
 insert into ib_conf_form(ID,PACKAGENAME,FORMNAME,FORMTITLE,FORMURL, ISEDIT,ISADD,ISDELETE,ISQUERY,ISEXCELEXPORT,ISIMPORTEXPORT,ISBPMFORM) values ('af21e2bf-3730-4fc8-af09-b91acba146d7','budgetmanage','operatBudgetPlan','经营预算年度计划申报表','/operatbudgetplan/operatbudgetplan-list.do',1,1,1,2,2,2,1);
/*======= 表单对应表 ==========*/
insert into ib_conf_form_table(PACKAGENAME,FORMNAME,TABLENAME,TABLETYPE) values ('budgetmanage','operatBudgetPlan','IB_OPERATBUDGETPLAN','main');
insert into ib_conf_form_table(PACKAGENAME,FORMNAME,TABLENAME,TABLETYPE) values ('budgetmanage','operatBudgetPlan','IB_OPERATBUDGETPLAN_S','sub');
/*======= 表单字段 ==========*/
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','operatBudgetPlan','IB_OPERATBUDGETPLAN.PLANYEAR','计划年','PLANYEAR','IB_OPERATBUDGETPLAN',1,'1','null','null','1','1','2','null','null','null');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','operatBudgetPlan','IB_OPERATBUDGETPLAN.PLANNAME','计划名称','PLANNAME','IB_OPERATBUDGETPLAN',2,'1','null','null','1','1','2','null','null','null');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','operatBudgetPlan','IB_OPERATBUDGETPLAN.DEPT','编制部门','DEPT','IB_OPERATBUDGETPLAN',3,'1','null','null','1','1','2','null','null','null');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','operatBudgetPlan','IB_OPERATBUDGETPLAN.EVENTTIME','编制时间','EVENTTIME','IB_OPERATBUDGETPLAN',4,'4','','','1','2','2','1','@currentDate','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','operatBudgetPlan','IB_OPERATBUDGETPLAN.NO','编号','NO','IB_OPERATBUDGETPLAN',5,'1','null','null','1','1','2','null','null','null');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','operatBudgetPlan','IB_OPERATBUDGETPLAN.PLANAMOUNT','计划总数','PLANAMOUNT','IB_OPERATBUDGETPLAN',7,'1','null','null','1','1','2','null','null','null');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','operatBudgetPlan','IB_OPERATBUDGETPLAN.DEPTLEADER','科长审批','DEPTLEADER','IB_OPERATBUDGETPLAN',8,'1','null','null','1','1','2','null','null','null');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','operatBudgetPlan','IB_OPERATBUDGETPLAN.DIRECTORMANAGER','主管领导审批','DIRECTORMANAGER','IB_OPERATBUDGETPLAN',9,'1','null','null','1','1','2','null','null','null');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','operatBudgetPlan','IB_OPERATBUDGETPLAN.GENERALMANAGER','总经理审批','GENERALMANAGER','IB_OPERATBUDGETPLAN',10,'1','null','null','1','1','2','null','null','null');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','operatBudgetPlan','IB_OPERATBUDGETPLAN.PLANNER','计划员确认','PLANNER','IB_OPERATBUDGETPLAN',11,'1','null','null','1','1','2','null','null','null');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','operatBudgetPlan','IB_OPERATBUDGETPLAN.PROJECTTYPESUM','项目类别合计','PROJECTTYPESUM','IB_OPERATBUDGETPLAN',12,'1','null','null','1','1','2','null','null','null');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','operatBudgetPlan','IB_OPERATBUDGETPLAN.PROJECTNAMESUM','项目名称合计','PROJECTNAMESUM','IB_OPERATBUDGETPLAN',13,'1','null','null','1','1','2','null','null','null');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','operatBudgetPlan','IB_OPERATBUDGETPLAN.ISGM','是否需要总经理审批','ISGM','IB_OPERATBUDGETPLAN',14,'8','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','operatBudgetPlan','IB_OPERATBUDGETPLAN.ISDM','是否需要主管领导审批','ISDM','IB_OPERATBUDGETPLAN',15,'8','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','operatBudgetPlan','IB_OPERATBUDGETPLAN_S.PROJECTTYPE','资金项目类别','PROJECTTYPE','IB_OPERATBUDGETPLAN_S',1,'1','null','null','1','1','2','null','null','null');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','operatBudgetPlan','IB_OPERATBUDGETPLAN_S.PROJECTNAME','项目计划名称','PROJECTNAME','IB_OPERATBUDGETPLAN_S',2,'1','null','null','1','1','2','null','null','null');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','operatBudgetPlan','IB_OPERATBUDGETPLAN_S.MATERIALTYPE','材料类别','MATERIALTYPE','IB_OPERATBUDGETPLAN_S',3,'1','null','null','1','1','2','null','null','null');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','operatBudgetPlan','IB_OPERATBUDGETPLAN_S.MATERIALNAME','材料/用品/费用名称','MATERIALNAME','IB_OPERATBUDGETPLAN_S',4,'1','null','null','1','1','2','null','null','null');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','operatBudgetPlan','IB_OPERATBUDGETPLAN_S.SPEC','规格/型号','SPEC','IB_OPERATBUDGETPLAN_S',5,'1','null','null','1','1','2','null','null','null');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','operatBudgetPlan','IB_OPERATBUDGETPLAN_S.UNIT','单位','UNIT','IB_OPERATBUDGETPLAN_S',6,'1','null','null','1','1','2','null','null','null');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','operatBudgetPlan','IB_OPERATBUDGETPLAN_S.PRICE','单价','PRICE','IB_OPERATBUDGETPLAN_S',7,'1','null','null','1','1','2','null','null','null');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','operatBudgetPlan','IB_OPERATBUDGETPLAN_S.NUMB','数量','NUMB','IB_OPERATBUDGETPLAN_S',8,'1','null','null','1','1','2','null','null','null');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','operatBudgetPlan','IB_OPERATBUDGETPLAN_S.PLANAMOUNTS','计划数（元）','PLANAMOUNTS','IB_OPERATBUDGETPLAN_S',9,'1','null','null','1','1','2','null','null','null');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','operatBudgetPlan','IB_OPERATBUDGETPLAN_S.REASON','实施原因','REASON','IB_OPERATBUDGETPLAN_S',10,'1','null','null','1','1','2','null','null','null');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','operatBudgetPlan','IB_OPERATBUDGETPLAN_S.INFO','措施/内容','INFO','IB_OPERATBUDGETPLAN_S',11,'1','null','null','1','1','2','null','null','null');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','operatBudgetPlan','IB_OPERATBUDGETPLAN_S.DEPT','所属部门','DEPT','IB_OPERATBUDGETPLAN_S',12,'1','null','null','1','1','2','null','null','null');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('budgetmanage','operatBudgetPlan','IB_OPERATBUDGETPLAN_S.REMARK','备注','REMARK','IB_OPERATBUDGETPLAN_S',13,'1','null','null','1','1','2','null','null','null');
/*======= 表 ==========*/
insert into ib_conf_table(ID,PACKAGENAME,TABLENAME,TABLENAMECOMMENT,TABLETYPE, PARENTTABLEID,ISBPMTABLE) values ('ib_operatbudgetplan001','budgetmanage','IB_OPERATBUDGETPLAN','经营预算年度计划申报表','1','null',1);
insert into ib_conf_table(ID,PACKAGENAME,TABLENAME,TABLENAMECOMMENT,TABLETYPE, PARENTTABLEID,ISBPMTABLE) values ('ib_operatbudgetplan_s001','budgetmanage','IB_OPERATBUDGETPLAN_S','经营预算年度计划申报子表','2','null',1);
/*======= 表字段 ==========*/
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN','PLANYEAR','计划年','VARCHAR','32','是','',1);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN','PLANNAME','计划名称','VARCHAR','256','是','',2);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN','DEPT','编制部门','VARCHAR','128','是','',3);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN','EVENTTIME','编制时间','DATE','0','是','',4);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN','NO','编号','VARCHAR','64','是','',5);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN','PLANAMOUNT','计划总数','NUMBER','12,2','是','',7);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN','DEPTLEADER','科长审批','VARCHAR','512','是','',8);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN','DIRECTORMANAGER','主管领导审批','VARCHAR','512','是','',9);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN','GENERALMANAGER','总经理审批','VARCHAR','512','是','',10);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN','PLANNER','计划员确认','VARCHAR','512','是','',11);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN','PROJECTTYPESUM','项目类别合计','NUMBER','12,2','是','',12);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN','PROJECTNAMESUM','项目名称合计','NUMBER','12,2','是','',13);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN','ISGM','是否需要总经理审批','VARCHAR','16','是','',14);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN','ISDM','是否需要主管领导审批','VARCHAR','16','是','',15);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN','ID','UUID主键','VARCHAR','64','否','null',91);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN','EXECUTIONID','流程执行实例ID','VARCHAR','64','是','null',92);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN','CREATEDATEBPM','流程创建时间','DATETIME','','是','null',93);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN','NODENAME','流程节点名','VARCHAR','128','是','null',94);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN','@USERNAME','负责人名','VARCHAR','128','是','null',95);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN','ASSIGNEEUSER','负责人','VARCHAR','64','是','null',95);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN','DONEFLAG','流程结束标记','INTEGER','4','是','null',96);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN','TASKTITLE','流程实例标题','VARCHAR','256','是','null',97);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN_S','PROJECTTYPE','资金项目类别','VARCHAR','128','是','128',1);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN_S','PROJECTNAME','项目计划名称','VARCHAR','256','是','',2);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN_S','MATERIALTYPE','材料类别','VARCHAR','128','是','',3);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN_S','MATERIALNAME','材料/用品/费用名称','VARCHAR','128','是','',4);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN_S','SPEC','规格/型号','VARCHAR','64','是','',5);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN_S','UNIT','单位','VARCHAR','64','是','',6);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN_S','PRICE','单价','NUMBER','12,2','是','',7);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN_S','NUMB','数量','NUMBER','10','是','',8);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN_S','PLANAMOUNTS','计划数（元）','NUMBER','12,2','是','',9);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN_S','REASON','实施原因','VARCHAR','128','是','',10);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN_S','INFO','措施/内容','VARCHAR','512','是','',11);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN_S','DEPT','所属部门','VARCHAR','128','是','',12);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN_S','REMARK','备注','VARCHAR','512','是','',13);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN_S','ID','UUID主键','VARCHAR','64','否','null',91);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_OPERATBUDGETPLAN_S','PARENTID','主表UUID','VARCHAR','64','否','null',92);

