/* ======================== 预算管理 ====================  */
/* ====== 经营预算年度数据表 =====  */
DROP TABLE IF EXISTS IB_OPERATBUDGETYEAR;
CREATE TABLE IB_OPERATBUDGETYEAR (PLANYEAR VARCHAR(32), PROJECTTYPE VARCHAR(128), PROJECTNAME VARCHAR(256), CHANGEPLANAM DOUBLE(12,2), ADDPLANAMOUNT DOUBLE(12,2), PLANAMOUNT DOUBLE(12,2), YEARPLANBALANCE DOUBLE(12,2), AMOUNT DOUBLE(12,2), DEPT VARCHAR(128), ID VARCHAR(64),  PRIMARY KEY (ID)) ENGINE=INNODB;
/* ====== 经营预算年度计划申报流程 =====  */
DROP TABLE IF EXISTS IB_OPERATBUDGETPLAN;
CREATE TABLE IB_OPERATBUDGETPLAN (PLANYEAR VARCHAR(32), PLANNAME VARCHAR(256), DEPT VARCHAR(128), EVENTTIME DATETIME, NO VARCHAR(64), PLANAMOUNT DOUBLE(12,2), DEPTLEADER VARCHAR(512), DIRECTORMANAGER VARCHAR(512), GENERALMANAGER VARCHAR(512), PLANNER VARCHAR(512), PROJECTTYPESUM DOUBLE(12,2), PROJECTNAMESUM DOUBLE(12,2), ISGM VARCHAR(16), ISDM VARCHAR(16), ID VARCHAR(64), EXECUTIONID VARCHAR(64), CREATEDATEBPM DATETIME, NODENAME VARCHAR(128), USERNAME VARCHAR(128), ASSIGNEEUSER VARCHAR(64), DONEFLAG INT(4), TASKTITLE VARCHAR(256),  PRIMARY KEY (ID)) ENGINE=INNODB;
DROP TABLE IF EXISTS IB_OPERATBUDGETPLAN_S;
CREATE TABLE IB_OPERATBUDGETPLAN_S (PROJECTTYPE VARCHAR(128), PROJECTNAME VARCHAR(256), MATERIALTYPE VARCHAR(128), MATERIALNAME VARCHAR(128), SPEC VARCHAR(64), UNIT VARCHAR(64), PRICE DOUBLE(12,2), NUMB INT(10), PLANAMOUNTS DOUBLE(12,2), REASON VARCHAR(128), INFO VARCHAR(512), DEPT VARCHAR(128), REMARK VARCHAR(512), ID VARCHAR(64), PARENTID VARCHAR(64),  PRIMARY KEY (ID)) ENGINE=INNODB;

