/* ======================== 业务模块组件管理表 ====================  */
/* ========================= 客户管理表 ========================  */
DROP TABLE IF EXISTS IB_CUSTOMER_INFO;
CREATE TABLE IB_CUSTOMER_INFO (
  ID                              varchar(64) NOT NULL,
  CUSTOMERNO         varchar(64),
  CUSTOMERSTATE   varchar(16),
  CUSTOMERNAME   varchar(64),
  CUSTOMERTYPE     varchar(32),
  CUSTOMERADDRESS varchar(512),
  PHONE                     varchar(32),
  TELEPHONE            varchar(32),
  SALESMANAGER     varchar(32),
  SYSTEMSALES          varchar(32),
  INFOSOURCE               varchar(16),
  RELATIONSHIPSTATUS varchar(16),
  PROVINCE                    varchar(16),
  CITY                              varchar(16),
  CUSTOMERNATURE    varchar(16),
  SUPERVISEUNIT varchar(64),
  PLANINFO varchar(512),
  CUSTOMERDEMAND varchar(256),
  COOPERATIONINFO varchar(2),
  INVOICENAME varchar(64),
  BANK varchar(64),
  ACCOUNTNO varchar(32),
  TAXID varchar(32),
  INVOICEUSER varchar(32),
  INVOICEUSERTEL varchar(16),
  INVOICEMAILUNITNAME varchar(64),
  MAILADDRESS varchar(128),
  INVOICZIP varchar(10),
  INVOICADDRESSEE varchar(64),
  INVOICPHONETEL varchar(16),
  CUSTOMERUSER varchar(32),
  USERPOSITION varchar(32),
  USERTELEPHONE varchar(32),
  USERPHONE varchar(32),
  USEREMAIL                    varchar(32),
  USEROFFICEADDRESS varchar(64),
  USERZIP                        varchar(10),
  PRIMARY KEY (ID)
) ENGINE=INNODB;
/* ===================== 原材料供应商维护表 ========================  */
DROP TABLE IF EXISTS IB_SUPPLIER;
CREATE TABLE IB_SUPPLIER (
    ID varchar(64) NOT NULL DEFAULT '',
  ACCOUNTNO varchar(32),
  BENEFICIARY varchar(128),
  BUSINESSCONTACTS varchar(16),
  CATEGORY varchar(8),
  COMPANYFAX varchar(16),
  COMPANYPHONE varchar(16),
  CONTACTFAX varchar(16),
  CONTACTMOBILEPHONE varchar(16),
  CONTACTTELEPHONE varchar(16),
  ENROLLTIME varchar(16),
  ESTINATIONCITY varchar(128),
  FINANCIALCALL varchar(16),
  FINANCIALCONTACTS varchar(16),
  FINANCIALFAX varchar(16),
  FINANCIALPHONE varchar(16),
  INFORMATION varchar(32),
  PRODUCT varchar(32),
  REGISTERED varchar(16),
  REMITTANCENAME varchar(128),
  SUPPLIERNUMBER varchar(32),
  TAXNO varchar(32),
  TELEPHONE varchar(16),
  UNITNAME varchar(128),
  UPDATAS varchar(256),
  URL varchar(32),
  USERADDRESS varchar(128),
  USERFAX varchar(16),
  USERMOBILEPHONE varchar(16),
  USERPERSON varchar(16),
  USERPHONE varchar(16),
  YOURADDRESS varchar(128),
  YOURCOMPANY varchar(128),
  YOURNAME varchar(32),
  YOURPHONE varchar(16),
  PRIMARY KEY (ID)
) ENGINE=INNODB;
