/* ==========================================================================================  */
/* =============================  IB_CONF_COMPONENT 业务模块组件管理表    =============================  */
/* ==========================================================================================  */
INSERT INTO IB_CONF_COMPONENT(ID,PACKAGENAME,MODULENAME,PARENTID,TYPEID) VALUES('designmanage0000','designmanage','设计部模块','0','sModule');
INSERT INTO IB_CONF_COMPONENT(ID,PACKAGENAME,MODULENAME,PARENTID,TYPEID) VALUES('designmanage0001','designmanage','表存储设计器','designmanage0000','Table');
INSERT INTO IB_CONF_COMPONENT(ID,PACKAGENAME,MODULENAME,PARENTID,TYPEID) VALUES('designmanage0002','designmanage','表单设计器','designmanage0000','Form');
INSERT INTO IB_CONF_COMPONENT(ID,PACKAGENAME,MODULENAME,PARENTID,TYPEID) VALUES('designmanage0003','designmanage','流程表设计器','designmanage0000','BpmTable');
INSERT INTO IB_CONF_COMPONENT(ID,PACKAGENAME,MODULENAME,PARENTID,TYPEID) VALUES('designmanage0004','designmanage','流程表单设计器','designmanage0000','BpmForm');
INSERT INTO IB_CONF_COMPONENT(ID,PACKAGENAME,MODULENAME,PARENTID,TYPEID) VALUES('designmanage0005','designmanage','流程设计器','designmanage0000','Bpm');
/* ================= 菜单管理表  ================== */
INSERT INTO IB_MENU(ID,MENUNAME,MENULEVEL,MENUURL,MENUIFRAME,MENUORDER,PARENTID) VALUES('designmanageOne','设计部模块','1','#','URL','7','0');
INSERT INTO IB_MENU(ID,MENUNAME,MENULEVEL,MENUURL,MENUIFRAME, MENUORDER,PARENTID) VALUES('designmanageTwo1','设计部模块','2','#','URL','1','designmanageOne');
INSERT INTO IB_MENU(ID,MENUNAME,MENULEVEL,MENUURL,MENUIFRAME, MENUORDER,PARENTID) VALUES('designmanageThree11','装饰进度管理页面','3','/project_progress/project_progress-list.do','URL','1','designmanageTwo1');
INSERT INTO IB_MENU(ID,MENUNAME,MENULEVEL,MENUURL,MENUIFRAME, MENUORDER,PARENTID) VALUES('designmanageThree12','自动报价页面','3','/autoquote/autoquote-input.do','URL','2','designmanageTwo1');
INSERT INTO IB_MENU(ID,MENUNAME,MENULEVEL,MENUURL,MENUIFRAME, MENUORDER,PARENTID) VALUES('designmanageThree13','合同管理','3','/contract_manage/contract_manage-list.do','URL','3','designmanageTwo1');

/*=============== 菜单和角色模板关联表  =============================*/
INSERT INTO IB_MENU_ROLE_DEF(MENU_ID,ROLE_DEF_ID) VALUES('designmanageOne','2');
INSERT INTO IB_MENU_ROLE_DEF(MENU_ID,ROLE_DEF_ID) VALUES('designmanageTwo1','2');
INSERT INTO IB_MENU_ROLE_DEF(MENU_ID,ROLE_DEF_ID) VALUES('designmanageThree11','2');
INSERT INTO IB_MENU_ROLE_DEF(MENU_ID,ROLE_DEF_ID) VALUES('designmanageThree12','2');

/* ================================================================================   */
/* ================================ 自动报价页面   =================================   */
/* ================================================================================   */
/*======= 表单 ==========*/
insert into ib_conf_form(ID,PACKAGENAME,FORMNAME,FORMTITLE,FORMURL, ISEDIT,ISADD,ISDELETE,ISQUERY,ISEXCELEXPORT,ISIMPORTEXPORT,ISBPMFORM) values ('designmanage-AUTOQUOTE0001','designmanage','AUTOQUOTE','自动报价页面','/autoquote/autoquote-list.do',1,1,1,2,2,2,2);
/*======= 表单对应表 ==========*/
insert into ib_conf_form_table(PACKAGENAME,FORMNAME,TABLENAME,TABLETYPE) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE','main');
insert into ib_conf_form_table(PACKAGENAME,FORMNAME,TABLENAME,TABLETYPE) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE_BATH','sub');
insert into ib_conf_form_table(PACKAGENAME,FORMNAME,TABLENAME,TABLETYPE) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE_BEDROOM','sub');
insert into ib_conf_form_table(PACKAGENAME,FORMNAME,TABLENAME,TABLETYPE) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE_HALL','sub');
insert into ib_conf_form_table(PACKAGENAME,FORMNAME,TABLENAME,TABLETYPE) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE_KITCHEN','sub');
insert into ib_conf_form_table(PACKAGENAME,FORMNAME,TABLENAME,TABLETYPE) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE_VERANDA','sub');
/*======= 表单字段 ==========*/
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE.CEILINGAREA','吊顶面积','CEILINGAREA','IB_AUTOQUOTE',1,'5','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE.TILEAREA','瓷砖面积','TILEAREA','IB_AUTOQUOTE',2,'5','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE.TILEAMOUNT','瓷砖金额','TILEAMOUNT','IB_AUTOQUOTE',2,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE.TILEUPRICE','瓷砖单价','TILEUPRICE','IB_AUTOQUOTE',2,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE.FLOORAMOUNT','地板金额','FLOORAMOUNT','IB_AUTOQUOTE',2,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE.FLOORUPRICE','地板单价','FLOORUPRICE','IB_AUTOQUOTE',2,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE.PAINTAMOUNT','涂料金额','PAINTAMOUNT','IB_AUTOQUOTE',2,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE.PAINTUPRICE','涂料单价','PAINTUPRICE','IB_AUTOQUOTE',2,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE.CEILINGAMOUNT','吊顶金额','CEILINGAMOUNT','IB_AUTOQUOTE',2,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE.CEILINGUPRICE','吊顶单价','CEILINGUPRICE','IB_AUTOQUOTE',2,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE.ARTIFICIALAMOUNT','人工费','ARTIFICIALAMOUNT','IB_AUTOQUOTE',2,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE.FLOORAREA','地板面积','FLOORAREA','IB_AUTOQUOTE',3,'5','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE.PAINTAREA','墙漆/涂料面积','PAINTAREA','IB_AUTOQUOTE',4,'5','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE.TOTALBUILDAREA','总建筑面积','TOTALBUILDAREA','IB_AUTOQUOTE',5,'5','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE.TOTALUSERAREA','总使用面积','TOTALUSERAREA','IB_AUTOQUOTE',6,'5','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE.TOTALAMOUNT','总金额','TOTALAMOUNT','IB_AUTOQUOTE',7,'5','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE_BATH.BATHAREA','浴室/洗手间子表.面积','BATHAREA','IB_AUTOQUOTE_BATH',1,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE_BATH.DOORAREA','浴室/洗手间子表.门窗等刨除面积','DOORAREA','IB_AUTOQUOTE_BATH',2,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE_BATH.BATHDEPTH','浴室/洗手间子表.长','BATHDEPTH','IB_AUTOQUOTE_BATH',3,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE_BATH.BATHWIDTH','浴室/洗手间子表.宽','BATHWIDTH','IB_AUTOQUOTE_BATH',4,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE_BATH.BATHHEIGHT','浴室/洗手间子表.高','BATHHEIGHT','IB_AUTOQUOTE_BATH',5,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE_BEDROOM.BEDROOMAREA','卧室.面积','BEDROOMAREA','IB_AUTOQUOTE_BEDROOM',1,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE_BEDROOM.DOORAREA','卧室.门窗等刨除面积','DOORAREA','IB_AUTOQUOTE_BEDROOM',2,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE_BEDROOM.BEDROOMDEPTH','卧室.长','BEDROOMDEPTH','IB_AUTOQUOTE_BEDROOM',3,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE_BEDROOM.BEDROOMWIDTH','卧室.宽','BEDROOMWIDTH','IB_AUTOQUOTE_BEDROOM',4,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE_BEDROOM.BEDROOMHEIGHT','卧室.高','BEDROOMHEIGHT','IB_AUTOQUOTE_BEDROOM',5,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE_HALL.HALLAREA','客厅.面积','HALLAREA','IB_AUTOQUOTE_HALL',1,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE_HALL.DOORAREA','客厅.门窗等刨除面积','DOORAREA','IB_AUTOQUOTE_HALL',2,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE_HALL.HALLDEPTH','客厅.长','HALLDEPTH','IB_AUTOQUOTE_HALL',3,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE_HALL.HALLWIDTH','客厅.宽','HALLWIDTH','IB_AUTOQUOTE_HALL',4,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE_HALL.HALLHEIGHT','客厅.高','HALLHEIGHT','IB_AUTOQUOTE_HALL',5,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE_KITCHEN.KITCHENAREA','厨房.面积','KITCHENAREA','IB_AUTOQUOTE_KITCHEN',1,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE_KITCHEN.DOORAREA','厨房.门窗等刨除面积','DOORAREA','IB_AUTOQUOTE_KITCHEN',2,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE_KITCHEN.KITCHENDEPTH','厨房.长','KITCHENDEPTH','IB_AUTOQUOTE_KITCHEN',3,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE_KITCHEN.KITCHENWIDTH','厨房.宽','KITCHENWIDTH','IB_AUTOQUOTE_KITCHEN',4,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE_KITCHEN.KITCHENHEIGHT','厨房.高','KITCHENHEIGHT','IB_AUTOQUOTE_KITCHEN',5,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE_VERANDA.VERANDAAREA','阳台.面积','VERANDAAREA','IB_AUTOQUOTE_VERANDA',1,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE_VERANDA.DOORAREA','阳台.门窗等刨除面积','DOORAREA','IB_AUTOQUOTE_VERANDA',2,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE_VERANDA.VERANDADEPTH','阳台.长','VERANDADEPTH','IB_AUTOQUOTE_VERANDA',3,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE_VERANDA.VERANDAWIDTH','阳台.宽','VERANDAWIDTH','IB_AUTOQUOTE_VERANDA',4,'1','','','1','1','2','','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','AUTOQUOTE','IB_AUTOQUOTE_VERANDA.VERANDAHEIGHT','阳台.高','VERANDAHEIGHT','IB_AUTOQUOTE_VERANDA',5,'1','','','1','1','2','','','');
/*======= 表 ==========*/
insert into ib_conf_table(ID,PACKAGENAME,TABLENAME,TABLENAMECOMMENT,TABLETYPE, PARENTTABLEID,ISBPMTABLE) values ('designmanage-IB_AUTOQUOTE0001','designmanage','IB_AUTOQUOTE','自动报价','1','null',2);
insert into ib_conf_table(ID,PACKAGENAME,TABLENAME,TABLENAMECOMMENT,TABLETYPE, PARENTTABLEID,ISBPMTABLE) values ('designmanage-IB_AUTOQUOTE_BATH0001','designmanage','IB_AUTOQUOTE_BATH','浴室/洗手间子表','2','null',2);
insert into ib_conf_table(ID,PACKAGENAME,TABLENAME,TABLENAMECOMMENT,TABLETYPE, PARENTTABLEID,ISBPMTABLE) values ('designmanage-IB_AUTOQUOTE_BEDROOM0001','designmanage','IB_AUTOQUOTE_BEDROOM','卧室','2','null',2);
insert into ib_conf_table(ID,PACKAGENAME,TABLENAME,TABLENAMECOMMENT,TABLETYPE, PARENTTABLEID,ISBPMTABLE) values ('designmanage-IB_AUTOQUOTE_HALL0001','designmanage','IB_AUTOQUOTE_HALL','客厅','2','null',2);
insert into ib_conf_table(ID,PACKAGENAME,TABLENAME,TABLENAMECOMMENT,TABLETYPE, PARENTTABLEID,ISBPMTABLE) values ('designmanage-IB_AUTOQUOTE_KITCHEN0001','designmanage','IB_AUTOQUOTE_KITCHEN','厨房','2','null',2);
insert into ib_conf_table(ID,PACKAGENAME,TABLENAME,TABLENAMECOMMENT,TABLETYPE, PARENTTABLEID,ISBPMTABLE) values ('designmanage-IB_AUTOQUOTE_VERANDA0001','designmanage','IB_AUTOQUOTE_VERANDA','阳台','2','null',2);
/*======= 表字段 ==========*/
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE','CEILINGAREA','吊顶面积','NUMBER','12,2','是','',1);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE','TILEAREA','瓷砖面积','NUMBER','12,2','是','',2);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE','FLOORAREA','地板面积','NUMBER','12,2','是','',3);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE','PAINTAREA','墙漆/涂料面积','NUMBER','12,2','是','',4);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE','TOTALBUILDAREA','总建筑面积','NUMBER','12,2','是','',5);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE','TOTALUSERAREA','总使用面积','NUMBER','12,2','是','',6);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE','TOTALAMOUNT','总金额','NUMBER','15,2','是','',7);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE','CEILINGUPRICE','吊顶单价','NUMBER','12,2','是','',8);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE','CEILINGAMOUNT','吊顶金额','NUMBER','12,2','是','',9);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE','TILEUPRICE','瓷砖单价','NUMBER','12,2','是','',10);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE','TILEAMOUNT','瓷砖金额','NUMBER','12,2','是','',11);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE','FLOORUPRICE','地板单价','NUMBER','12,2','是','',12);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE','FLOORAMOUNT','地板金额','NUMBER','12,2','是','',13);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE','PAINTUPRICE','涂料单价','NUMBER','12,2','是','',14);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE','PAINTAMOUNT','涂料金额','NUMBER','12,2','是','',15);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE','ARTIFICIALAMOUNT','人工费','NUMBER','12,2','是','',16);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE','ID','UUID主键','VARCHAR','64','否','',91);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE','SCOPEID','范围','VARCHAR','64','否','',92);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_BATH','BATHAREA','面积','NUMBER','12,2','是','',1);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_BATH','DOORAREA','门窗等刨除面积','NUMBER','12,2','是','',2);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_BATH','BATHDEPTH','长','NUMBER','12,2','是','',3);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_BATH','BATHWIDTH','宽','NUMBER','12,2','是','',4);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_BATH','BATHHEIGHT','高','NUMBER','12,2','是','',5);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_BATH','ID','UUID主键','VARCHAR','64','否','',91);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_BATH','PARENTID','主表UUID','VARCHAR','64','否','',92);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_BEDROOM','BEDROOMAREA','面积','NUMBER','12,2','是','',1);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_BEDROOM','DOORAREA','门窗等刨除面积','NUMBER','12,2','是','',2);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_BEDROOM','BEDROOMDEPTH','长','NUMBER','12,2','是','',3);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_BEDROOM','BEDROOMWIDTH','宽','NUMBER','12,2','是','',4);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_BEDROOM','BEDROOMHEIGHT','高','NUMBER','12,2','是','',5);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_BEDROOM','ID','UUID主键','VARCHAR','64','否','',91);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_BEDROOM','PARENTID','主表UUID','VARCHAR','64','否','',92);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_HALL','HALLAREA','面积','NUMBER','12,2','是','',1);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_HALL','DOORAREA','门窗等刨除面积','NUMBER','12,2','是','',2);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_HALL','HALLDEPTH','长','NUMBER','12,2','是','',3);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_HALL','HALLWIDTH','宽','NUMBER','12,2','是','',4);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_HALL','HALLHEIGHT','高','NUMBER','12,2','是','',5);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_HALL','ID','UUID主键','VARCHAR','64','否','',91);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_HALL','PARENTID','主表UUID','VARCHAR','64','否','',92);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_KITCHEN','KITCHENAREA','面积','NUMBER','12,2','是','',1);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_KITCHEN','DOORAREA','门窗等刨除面积','NUMBER','12,2','是','',2);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_KITCHEN','KITCHENDEPTH','长','NUMBER','12,2','是','',3);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_KITCHEN','KITCHENWIDTH','宽','NUMBER','12,2','是','',4);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_KITCHEN','KITCHENHEIGHT','高','NUMBER','12,2','是','',5);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_KITCHEN','ID','UUID主键','VARCHAR','64','否','',91);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_KITCHEN','PARENTID','主表UUID','VARCHAR','64','否','',92);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_VERANDA','VERANDAAREA','面积','NUMBER','12,2','是','',1);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_VERANDA','DOORAREA','门窗等刨除面积','NUMBER','12,2','是','',2);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_VERANDA','VERANDADEPTH','长','NUMBER','12,2','是','',3);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_VERANDA','VERANDAWIDTH','宽','NUMBER','12,2','是','',4);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_VERANDA','VERANDAHEIGHT','高','NUMBER','12,2','是','',5);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_VERANDA','ID','UUID主键','VARCHAR','64','否','',91);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_AUTOQUOTE_VERANDA','PARENTID','主表UUID','VARCHAR','64','否','',92);
/* ================================ 自动报价数据   =================================   */
insert into ib_autoquote(CEILINGAREA,TILEAREA,FLOORAREA,PAINTAREA,TOTALBUILDAREA,TOTALUSERAREA,TOTALAMOUNT,ID,SCOPEID,CEILINGUPRICE,CEILINGAMOUNT,TILEUPRICE,TILEAMOUNT,FLOORUPRICE,FLOORAMOUNT,PAINTUPRICE,PAINTAMOUNT,ARTIFICIALAMOUNT) values (25.00,103.20,65.00,192.80,NULL,90.00,44604.00,'ib_autoquote0001','1',200.00,2500.00,200.00,10320.00,200.00,26000.00,10.00,5784.00,20000.00);
insert into ib_autoquote_bath(ID,PARENTID,BATHAREA,DOORAREA,BATHDEPTH,BATHWIDTH,BATHHEIGHT) values ('ib_autoquote_bath0001','',12.00,4.00,4.00,3.00,2.80);
insert into ib_autoquote_bedroom(ID,PARENTID,BEDROOMAREA,DOORAREA,BEDROOMDEPTH,BEDROOMWIDTH,BEDROOMHEIGHT) values ('ib_autoquote_bedroom0001','',20.00,8.00,5.00,4.00,2.80);
insert into ib_autoquote_hall(ID,PARENTID,HALLAREA,DOORAREA,HALLDEPTH,HALLWIDTH,HALLHEIGHT) values ('ib_autoquote_hall0001','',30.00,15.00,6.00,5.00,2.80);
insert into ib_autoquote_kitchen(ID,PARENTID,KITCHENAREA,DOORAREA,KITCHENDEPTH,KITCHENWIDTH,KITCHENHEIGHT) values ('ib_autoquote_kitchen0001','',9.00,8.00,3.00,3.00,2.80);
insert into ib_autoquote_veranda(ID,PARENTID,VERANDAAREA,DOORAREA,VERANDADEPTH,VERANDAWIDTH,VERANDAHEIGHT) values ('ib_autoquote_veranda0001','',4.00,5.00,2.00,2.00,2.80);

/* ================================================================================   */
/* ================================ 工程进度管理页面   =================================   */
/* ================================================================================   */
/*======= 表单 ==========*/
insert into ib_conf_form(ID,PACKAGENAME,FORMNAME,FORMTITLE,FORMURL, ISEDIT,ISADD,ISDELETE,ISQUERY,ISEXCELEXPORT,ISIMPORTEXPORT,ISBPMFORM) values ('6cceaa15-476b-4ddb-8da4-a58300e77a8f','designmanage','projectprogress','工程进度管理','/project_progress/project_progress-list.do',1,1,1,1,1,2,2);
/*======= 表单对应表 ==========*/
insert into ib_conf_form_table(PACKAGENAME,FORMNAME,TABLENAME,TABLETYPE) values ('designmanage','projectprogress','IB_PP_DEMOLITION_IMG','sub');
insert into ib_conf_form_table(PACKAGENAME,FORMNAME,TABLENAME,TABLETYPE) values ('designmanage','projectprogress','IB_PP_DESIGN_IMG','sub');
insert into ib_conf_form_table(PACKAGENAME,FORMNAME,TABLENAME,TABLETYPE) values ('designmanage','projectprogress','IB_PP_DONE_IMG','sub');
insert into ib_conf_form_table(PACKAGENAME,FORMNAME,TABLENAME,TABLETYPE) values ('designmanage','projectprogress','IB_PP_FLOOR_IMG','sub');
insert into ib_conf_form_table(PACKAGENAME,FORMNAME,TABLENAME,TABLETYPE) values ('designmanage','projectprogress','IB_PP_METAL_IMG','sub');
insert into ib_conf_form_table(PACKAGENAME,FORMNAME,TABLENAME,TABLETYPE) values ('designmanage','projectprogress','IB_PP_SURFACE_IMG','sub');
insert into ib_conf_form_table(PACKAGENAME,FORMNAME,TABLENAME,TABLETYPE) values ('designmanage','projectprogress','IB_PP_TILE_IMG','sub');
insert into ib_conf_form_table(PACKAGENAME,FORMNAME,TABLENAME,TABLETYPE) values ('designmanage','projectprogress','IB_PP_WALL_IMG','sub');
insert into ib_conf_form_table(PACKAGENAME,FORMNAME,TABLENAME,TABLETYPE) values ('designmanage','projectprogress','IB_PP_WATER_IMG','sub');
insert into ib_conf_form_table(PACKAGENAME,FORMNAME,TABLENAME,TABLETYPE) values ('designmanage','projectprogress','IB_PROJECT_PROGRESS','main');
/*======= 表单字段 ==========*/
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','projectprogress','IB_PP_DEMOLITION_IMG.IMGURL','图片地址','IMGURL','IB_PP_DEMOLITION_IMG',1,'11','','','1','1','2','2','','{"pathName":"progress"}');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','projectprogress','IB_PP_DEMOLITION_IMG.IMGINFO','图片信息描述','IMGINFO','IB_PP_DEMOLITION_IMG',2,'2','','','1','1','2','2','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','projectprogress','IB_PP_DESIGN_IMG.IMGURL','图片地址','IMGURL','IB_PP_DESIGN_IMG',1,'11','','','1','1','2','1','','{"pathName":"progress"}');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','projectprogress','IB_PP_DESIGN_IMG.IMGINFO','图片信息描述','IMGINFO','IB_PP_DESIGN_IMG',2,'2','','','1','1','2','2','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','projectprogress','IB_PP_DONE_IMG.IMGURL','图片地址','IMGURL','IB_PP_DONE_IMG',1,'11','','','1','1','2','1','','{"pathName":"progress"}');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','projectprogress','IB_PP_DONE_IMG.IMGINFO','图片信息描述','IMGINFO','IB_PP_DONE_IMG',2,'2','','','1','1','2','2','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','projectprogress','IB_PP_FLOOR_IMG.IMGURL','图片地址','IMGURL','IB_PP_FLOOR_IMG',2,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','projectprogress','IB_PP_FLOOR_IMG.IMGINFO','图片信息描述','IMGINFO','IB_PP_FLOOR_IMG',2,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','projectprogress','IB_PP_METAL_IMG.IMGURL','图片地址','IMGURL','IB_PP_METAL_IMG',2,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','projectprogress','IB_PP_METAL_IMG.IMGINFO','图片信息描述','IMGINFO','IB_PP_METAL_IMG',2,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','projectprogress','IB_PP_SURFACE_IMG.IMGURL','图片地址','IMGURL','IB_PP_SURFACE_IMG',1,'11','','','1','1','2','1','','{"pathName":"progress"}');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','projectprogress','IB_PP_SURFACE_IMG.IMGINFO','图片信息描述','IMGINFO','IB_PP_SURFACE_IMG',2,'2','','','1','1','2','2','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','projectprogress','IB_PP_TILE_IMG.IMGURL','图片地址','IMGURL','IB_PP_TILE_IMG',1,'11','','','1','1','2','1','','{"pathName":"progress"}');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','projectprogress','IB_PP_TILE_IMG.IMGINFO','图片信息描述','IMGINFO','IB_PP_TILE_IMG',2,'2','','','1','1','2','2','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','projectprogress','IB_PP_WALL_IMG.IMGURL','图片地址','IMGURL','IB_PP_WALL_IMG',1,'11','','','1','1','2','1','','{"pathName":"progress"}');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','projectprogress','IB_PP_WALL_IMG.IMGINFO','图片信息描述','IMGINFO','IB_PP_WALL_IMG',2,'2','','','1','1','2','2','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','projectprogress','IB_PP_WATER_IMG.IMGURL','图片地址','IMGURL','IB_PP_WATER_IMG',1,'11','','','1','1','2','1','','{"pathName":"progress"}');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','projectprogress','IB_PP_WATER_IMG.IMGINFO','图片信息描述','IMGINFO','IB_PP_WATER_IMG',2,'2','','','1','1','2','2','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','projectprogress','IB_PROJECT_PROGRESS.PACTNO','合同编号','PACTNO','IB_PROJECT_PROGRESS',1,'1','','','1','1','2','2','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','projectprogress','IB_PROJECT_PROGRESS.DONEFLAG','竣工验收完成','DONEFLAG','IB_PROJECT_PROGRESS',2,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','projectprogress','IB_PROJECT_PROGRESS.TILEFLAG','泥瓦工程完成','TILEFLAG','IB_PROJECT_PROGRESS',2,'8','','','1','1','2','1','2','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','projectprogress','IB_PROJECT_PROGRESS.WALLFLAG','油漆工程完成','WALLFLAG','IB_PROJECT_PROGRESS',2,'8','','','1','1','2','1','2','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','projectprogress','IB_PROJECT_PROGRESS.FLOORFLAG','木工工程完成','FLOORFLAG','IB_PROJECT_PROGRESS',2,'8','','','1','1','2','1','2','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','projectprogress','IB_PROJECT_PROGRESS.METALFLAG','金属工程完成','METALFLAG','IB_PROJECT_PROGRESS',2,'8','','','1','1','2','1','2','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','projectprogress','IB_PROJECT_PROGRESS.WATERFLAG','水电改造完成','WATERFLAG','IB_PROJECT_PROGRESS',2,'8','','','1','1','2','1','2','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','projectprogress','IB_PROJECT_PROGRESS.DESIGNFLAG','设计图完成','DESIGNFLAG','IB_PROJECT_PROGRESS',2,'8','','','1','1','2','1','2','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','projectprogress','IB_PROJECT_PROGRESS.SURFACEFLAG','表面工程完成','SURFACEFLAG','IB_PROJECT_PROGRESS',2,'8','','','1','1','2','1','2','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','projectprogress','IB_PROJECT_PROGRESS.CUSTOMERNAME','客户名称','CUSTOMERNAME','IB_PROJECT_PROGRESS',2,'10','','','1','1','1','1','','{"jsplist":[{"inputKey":"customername","inputValue":"customername","inputTitle":"客户名"},{"inputKey":"address1","inputValue":"customeraddress","inputTitle":"客户地址"}],"className":"com.codegenerate.crmmanage.service.Customer_infoService","queryTitle":"客户名","queryName":"customername"}');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','projectprogress','IB_PROJECT_PROGRESS.DEMOLITIONFLAG','拆改完成','DEMOLITIONFLAG','IB_PROJECT_PROGRESS',2,'8','','','1','1','2','1','2','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','projectprogress','IB_PROJECT_PROGRESS.PROJECTNAME','工程项目名称','PROJECTNAME','IB_PROJECT_PROGRESS',3,'1','','','1','1','1','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','projectprogress','IB_PROJECT_PROGRESS.DESIGNNAME','设计师名','DESIGNNAME','IB_PROJECT_PROGRESS',4,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','projectprogress','IB_PROJECT_PROGRESS.WORKSMANAGE','工长名字','WORKSMANAGE','IB_PROJECT_PROGRESS',5,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','projectprogress','IB_PROJECT_PROGRESS.CURRENTPROGRESS','当前进度','CURRENTPROGRESS','IB_PROJECT_PROGRESS',6,'6','','','1','1','2','2','','[{"key":"1","value":"未开启"},{"key":"2","value":"签订合同"},{"key":"3","value":"设计完成"},{"key":"4","value":"工程进行中"},{"key":"5","value":"施工完成"},{"key":"6","value":"验收完成"}]');
/*======= 表 ==========*/
insert into ib_conf_table(ID,PACKAGENAME,TABLENAME,TABLENAMECOMMENT,TABLETYPE, PARENTTABLEID,ISBPMTABLE) values ('21356b40-9119-4199-96ee-cc12c373fb2d','designmanage','IB_PP_DEMOLITION_IMG','进度拆改图片子表','2','null',2);
insert into ib_conf_table(ID,PACKAGENAME,TABLENAME,TABLENAMECOMMENT,TABLETYPE, PARENTTABLEID,ISBPMTABLE) values ('c280c1df-8a63-4ebf-9ff4-d18fe0eeb9a5','designmanage','IB_PP_DESIGN_IMG','进度设计图子表','2','null',2);
insert into ib_conf_table(ID,PACKAGENAME,TABLENAME,TABLENAMECOMMENT,TABLETYPE, PARENTTABLEID,ISBPMTABLE) values ('a7668253-a38a-4f2a-8909-e2ef443f73c9','designmanage','IB_PP_DONE_IMG','进度竣工图子表','2','null',2);
insert into ib_conf_table(ID,PACKAGENAME,TABLENAME,TABLENAMECOMMENT,TABLETYPE, PARENTTABLEID,ISBPMTABLE) values ('f5403bd0-beee-4b64-926e-fad717a7009d','designmanage','IB_PP_FLOOR_IMG','进度木工工程图子表','2','null',2);
insert into ib_conf_table(ID,PACKAGENAME,TABLENAME,TABLENAMECOMMENT,TABLETYPE, PARENTTABLEID,ISBPMTABLE) values ('f9e86ddc-c70a-455f-a9e4-28c69ed2e6df','designmanage','IB_PP_METAL_IMG','进度金属工程图子表','2','null',2);
insert into ib_conf_table(ID,PACKAGENAME,TABLENAME,TABLENAMECOMMENT,TABLETYPE, PARENTTABLEID,ISBPMTABLE) values ('d1e0714f-f727-46ae-b262-54633f45094c','designmanage','IB_PP_SURFACE_IMG','进度表面工程图子表','2','null',2);
insert into ib_conf_table(ID,PACKAGENAME,TABLENAME,TABLENAMECOMMENT,TABLETYPE, PARENTTABLEID,ISBPMTABLE) values ('43c95ff1-d4c2-4f1b-b980-bfc540bf25a2','designmanage','IB_PP_TILE_IMG','进度泥瓦工程图子表','2','null',2);
insert into ib_conf_table(ID,PACKAGENAME,TABLENAME,TABLENAMECOMMENT,TABLETYPE, PARENTTABLEID,ISBPMTABLE) values ('31e437d5-9696-4095-9759-a6a485055a9f','designmanage','IB_PP_WALL_IMG','进度油漆工程图子表','2','null',2);
insert into ib_conf_table(ID,PACKAGENAME,TABLENAME,TABLENAMECOMMENT,TABLETYPE, PARENTTABLEID,ISBPMTABLE) values ('4a42a91f-0190-4c0f-878b-67f5b3c4397c','designmanage','IB_PP_WATER_IMG','进度水电改造图子表','2','null',2);
insert into ib_conf_table(ID,PACKAGENAME,TABLENAME,TABLENAMECOMMENT,TABLETYPE, PARENTTABLEID,ISBPMTABLE) values ('b8398b7b-064a-4105-85c5-f91ac247fcb8','designmanage','IB_PROJECT_PROGRESS','装饰进度管理表','1','null',2);
/*======= 表字段 ==========*/
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_DEMOLITION_IMG','IMGURL','图片地址','VARCHAR','256','是','',1);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_DEMOLITION_IMG','IMGINFO','图片信息描述','VARCHAR','128','是','',2);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_DEMOLITION_IMG','ID','UUID主键','VARCHAR','64','否','',91);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_DEMOLITION_IMG','PARENTID','主表UUID','VARCHAR','64','否','',92);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_DESIGN_IMG','IMGURL','图片地址','VARCHAR','256','是','',1);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_DESIGN_IMG','IMGINFO','图片信息描述','VARCHAR','128','是','',2);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_DESIGN_IMG','ID','UUID主键','VARCHAR','64','否','',91);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_DESIGN_IMG','PARENTID','主表UUID','VARCHAR','64','否','',92);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_DONE_IMG','IMGURL','图片地址','VARCHAR','256','是','',1);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_DONE_IMG','IMGINFO','图片信息描述','VARCHAR','128','是','',2);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_DONE_IMG','ID','UUID主键','VARCHAR','64','否','',91);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_DONE_IMG','PARENTID','主表UUID','VARCHAR','64','否','',92);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_FLOOR_IMG','IMGURL','图片地址','VARCHAR','256','是','',1);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_FLOOR_IMG','IMGINFO','图片信息描述','VARCHAR','128','是','',2);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_FLOOR_IMG','ID','UUID主键','VARCHAR','64','否','',91);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_FLOOR_IMG','PARENTID','主表UUID','VARCHAR','64','否','',92);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_METAL_IMG','IMGINFO','图片信息描述','VARCHAR','128','是','',2);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_METAL_IMG','IMGURL','图片地址','VARCHAR','256','是','',3);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_METAL_IMG','ID','UUID主键','VARCHAR','64','否','',91);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_METAL_IMG','PARENTID','主表UUID','VARCHAR','64','否','',92);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_SURFACE_IMG','IMGURL','图片地址','VARCHAR','256','是','',1);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_SURFACE_IMG','IMGINFO',' 图片信息描述','VARCHAR','128','是','',2);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_SURFACE_IMG','ID','UUID主键','VARCHAR','64','否','',91);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_SURFACE_IMG','PARENTID','主表UUID','VARCHAR','64','否','',92);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_TILE_IMG','IMGURL','图片地址','VARCHAR','256','是','',1);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_TILE_IMG','IMGINFO','图片信息描述','VARCHAR','128','是','',2);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_TILE_IMG','ID','UUID主键','VARCHAR','64','否','',91);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_TILE_IMG','PARENTID','主表UUID','VARCHAR','64','否','',92);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_WALL_IMG','IMGURL','图片地址','VARCHAR','256','是','',1);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_WALL_IMG','IMGINFO','图片信息描述','VARCHAR','128','是','',2);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_WALL_IMG','ID','UUID主键','VARCHAR','64','否','',91);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_WALL_IMG','PARENTID','主表UUID','VARCHAR','64','否','',92);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_WATER_IMG','IMGURL','图片地址','VARCHAR','256','是','',1);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_WATER_IMG','IMGINFO','图片信息描述','VARCHAR','128','是','',2);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_WATER_IMG','ID','UUID主键','VARCHAR','64','否','',91);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PP_WATER_IMG','PARENTID','主表UUID','VARCHAR','64','否','',92);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PROJECT_PROGRESS','PACTNO','合同编号','VARCHAR','64','是','',1);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PROJECT_PROGRESS','CUSTOMERNAME','客户名称','VARCHAR','64','是','',2);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PROJECT_PROGRESS','PROJECTNAME','工程项目名称','VARCHAR','64','是','',3);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PROJECT_PROGRESS','DESIGNNAME','设计师名','VARCHAR','64','是','',4);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PROJECT_PROGRESS','WORKSMANAGE','工长名字','VARCHAR','64','是','',5);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PROJECT_PROGRESS','CURRENTPROGRESS','当前进度','VARCHAR','16','是','',6);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PROJECT_PROGRESS','DESIGNFLAG','设计图完成','VARCHAR','8','是','',7);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PROJECT_PROGRESS','DEMOLITIONFLAG','拆改完成','VARCHAR','8','是','',8);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PROJECT_PROGRESS','WATERFLAG','水电改造完成','VARCHAR','8','是','',9);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PROJECT_PROGRESS','TILEFLAG','泥瓦工程图','VARCHAR','8','是','',10);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PROJECT_PROGRESS','METALFLAG','金属工程','VARCHAR','8','是','',11);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PROJECT_PROGRESS','WALLFLAG','油漆工程完成','VARCHAR','8','是','',12);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PROJECT_PROGRESS','FLOORFLAG','木工工程完成','VARCHAR','8','是','',13);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PROJECT_PROGRESS','SURFACEFLAG','表面工程','VARCHAR','8','是','',14);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PROJECT_PROGRESS','DONEFLAG','竣工验收完成','VARCHAR','8','是','',15);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PROJECT_PROGRESS','ID','UUID主键','VARCHAR','64','否','',91);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_PROJECT_PROGRESS','SCOPEID','范围','VARCHAR','64','否','',92);

/* ================================================================================   */
/* ================================ 合同管理页面   =================================   */
/* ================================================================================   */
/*======= 表单 ==========*/
insert into ib_conf_form(ID,PACKAGENAME,FORMNAME,FORMTITLE,FORMURL, ISEDIT,ISADD,ISDELETE,ISQUERY,ISEXCELEXPORT,ISIMPORTEXPORT,ISBPMFORM) values ('9559503a-02f1-4d90-ad02-bc8867e8e185','designmanage','CONTRACTMANAGE','合同管理','/contract_manage/contract_manage-list.do',1,1,1,1,2,2,2);
/*======= 表单对应表 ==========*/
insert into ib_conf_form_table(PACKAGENAME,FORMNAME,TABLENAME,TABLETYPE) values ('designmanage','CONTRACTMANAGE','IB_CONTRACT_MANAGE','main');
/*======= 表单字段 ==========*/
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','CONTRACTMANAGE','IB_CONTRACT_MANAGE.CONTRACTNAME','合同名称','CONTRACTNAME','IB_CONTRACT_MANAGE',1,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','CONTRACTMANAGE','IB_CONTRACT_MANAGE.CUSTOMERNAME','客户名称','CUSTOMERNAME','IB_CONTRACT_MANAGE',2,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','CONTRACTMANAGE','IB_CONTRACT_MANAGE.PROJECTNAME','工程项目名称','PROJECTNAME','IB_CONTRACT_MANAGE',3,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','CONTRACTMANAGE','IB_CONTRACT_MANAGE.CONTRACTURL','合同文件地址','CONTRACTURL','IB_CONTRACT_MANAGE',4,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','CONTRACTMANAGE','IB_CONTRACT_MANAGE.ADDRESS','客户地址','ADDRESS','IB_CONTRACT_MANAGE',5,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','CONTRACTMANAGE','IB_CONTRACT_MANAGE.CUSTOMERPHONE','客户电话','CUSTOMERPHONE','IB_CONTRACT_MANAGE',6,'1','','','1','1','2','1','','');
insert into ib_conf_form_table_colums(PACKAGENAME,FORMNAME,FORMCOLUMN,FORMCOLUMNTITLE,TABLECOLUMN, TABLENAME,COLUMNNO,FCTYPE,FCWIDTH,FCHEIGHT,FCDISPLAY,FCEDIT,FCQUERY,FCMUST,FCDEFAULT, CONFSELECTINFO) values ('designmanage','CONTRACTMANAGE','IB_CONTRACT_MANAGE.REMARK','备注','REMARK','IB_CONTRACT_MANAGE',7,'2','','','1','1','2','2','','');
/*======= 表 ==========*/
insert into ib_conf_table(ID,PACKAGENAME,TABLENAME,TABLENAMECOMMENT,TABLETYPE, PARENTTABLEID,ISBPMTABLE) values ('7ebf0eca-de3a-4624-9de3-2218df36f3a5','designmanage','IB_CONTRACT_MANAGE','合同管理','1','null',2);
/*======= 表字段 ==========*/
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_CONTRACT_MANAGE','CONTRACTNAME','合同名','VARCHAR','64','是','',1);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_CONTRACT_MANAGE','CUSTOMERNAME','客户名称','VARCHAR','64','是','',2);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_CONTRACT_MANAGE','PROJECTNAME','工程项目名称','VARCHAR','64','是','',3);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_CONTRACT_MANAGE','CONTRACTURL','合同文件地址','VARCHAR','256','是','',4);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_CONTRACT_MANAGE','ADDRESS','客户地址','VARCHAR','128','是','',5);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_CONTRACT_MANAGE','CUSTOMERPHONE','客户电话','VARCHAR','16','是','',6);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_CONTRACT_MANAGE','REMARK','备注','VARCHAR','512','是','',7);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_CONTRACT_MANAGE','ID','UUID主键','VARCHAR','64','否','',91);
insert into ib_conf_table_columns(tableName,columnValue,columnName,columnType,columnSize, isNull,defaultValue,columnNo) values ('IB_CONTRACT_MANAGE','SCOPEID','范围','VARCHAR','64','否','',92);


