package com.ibusiness.base.group.entity;

// Generated by Hibernate Tools
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * 部门表实体Department .
 * 
 * @author JiangBo
 */
@Entity
@Table(name = "IB_DEPARTMENT")
public class OrgDepartment implements java.io.Serializable {
    private static final long serialVersionUID = 0L;
    /** 编号. */
    private String id;
    /** 公司编号. */
    private String companyid;
    /** 公司名称 */
    private String companyName;
    /** 部门名称. */
    private String name;
    /** 备注. */
    private String descn;
    /** null. */
    private Integer status;
    /** null. */
    private String ref;
    /** null. */
    private String scopeid;

    public OrgDepartment() {
    }

    public OrgDepartment(String companyid, String name, String descn,
            Integer status, String ref, String scopeId) {
        this.companyid = companyid;
        this.name = name;
        this.descn = descn;
        this.status = status;
        this.ref = ref;
        this.scopeid = scopeId;
    }
    /** @return null. */
    @Id
    @Column(name = "ID", unique = true, nullable = false)
    public String getId() {
        return this.id;
    }
    /**
     * @param id
     *            null.
     */
    public void setId(String id) {
        this.id = id;
    }
    /**
     * @return the companyid
     */
    public String getCompanyid() {
        return companyid;
    }
    /**
     * @param companyid the companyid to set
     */
    public void setCompanyid(String companyid) {
        this.companyid = companyid;
    }
    /** @return null. */
    @Column(name = "NAME", length = 200)
    public String getName() {
        return this.name;
    }
    /**
     * @param name
     *            null.
     */
    public void setName(String name) {
        this.name = name;
    }
    /** @return null. */
    @Column(name = "DESCN", length = 200)
    public String getDescn() {
        return this.descn;
    }
    /**
     * @param descn
     *            null.
     */
    public void setDescn(String descn) {
        this.descn = descn;
    }
    /** @return null. */
    @Column(name = "STATUS")
    public Integer getStatus() {
        return this.status;
    }
    /**
     * @param status
     *            null.
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
    /** @return null. */
    @Column(name = "REF", length = 200)
    public String getRef() {
        return this.ref;
    }
    /**
     * @param ref
     *            null.
     */
    public void setRef(String ref) {
        this.ref = ref;
    }
    /**
	 * @return the scopeid
	 */
    @Column(name = "SCOPE_ID", length = 50)
	public String getScopeid() {
		return scopeid;
	}
	/**
	 * @param scopeid the scopeid to set
	 */
	public void setScopeid(String scopeid) {
		this.scopeid = scopeid;
	}

	@Transient
	public String getCompanyName() {
		return companyName;
	}
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}
}
