
CREATE TABLE BPM_CONF_BASE(
	ID BIGINT auto_increment,
	PROCESS_DEFINITION_ID VARCHAR(200),
	PROCESS_DEFINITION_KEY VARCHAR(200),
	PROCESS_DEFINITION_VERSION INT,
        CONSTRAINT PK_BPM_CONF_BASE PRIMARY KEY(ID)
) engine=innodb;

CREATE TABLE BPM_PROCESS(
	ID BIGINT auto_increment,
	NAME VARCHAR(200),
	CATEGORY_ID BIGINT,
	PRIORITY INTEGER,
	DESCN VARCHAR(200),
	CODE VARCHAR(64),
	CONF_BASE_ID BIGINT,
	USE_TASK_CONF INTEGER,
        CONSTRAINT PK_BPM_PROCESS PRIMARY KEY(ID),
        CONSTRAINT FK_BPM_PROCESS_CATEGORY_ID FOREIGN KEY(CATEGORY_ID) REFERENCES BPM_CATEGORY(ID)
) engine=innodb;

ALTER TABLE BPM_PROCESS ADD CONSTRAINT FK_BPM_PROCESS_CONF_BASE FOREIGN KEY(CONF_BASE_ID) REFERENCES BPM_CONF_BASE(ID);
