
CREATE TABLE BPM_PROCESS(
	ID BIGINT auto_increment,
	NAME VARCHAR(200),
	CATEGORY_ID BIGINT,
	PRIORITY INTEGER,
	DESCN VARCHAR(200),
	CODE VARCHAR(64),
	CONF_BASE_ID BIGINT,
	USE_TASK_CONF INTEGER,
        CONSTRAINT PK_BPM_PROCESS PRIMARY KEY(ID),
        CONSTRAINT FK_BPM_PROCESS_CATEGORY_ID FOREIGN KEY(CATEGORY_ID) REFERENCES BPM_CATEGORY(ID),
        CONSTRAINT FK_BPM_PROCESS_CONF_BASE FOREIGN KEY(CONF_BASE_ID) REFERENCES BPM_CONF_BASE(ID)
) engine=innodb;

