INSERT INTO SCOPE_INFO(ID,NAME,CODE,REF,SHARED,USER_REPO_REF,TYPE) VALUES(1,'默认','default','1',0,'1',0);
INSERT INTO SCOPE_INFO(ID,NAME,CODE,REF,SHARED,USER_REPO_REF,TYPE) VALUES(2,'cms','cms','2',0,'1',1);
