package com.tx.common.entity;

// Generated by Hibernate Tools
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserBase .
 * 
 * @author Lingo
 */
@Entity
@Table(name = "USER_BASE1")
public class CommonEntity implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** null. */
    private Long id;

    /** null. */
    private String username;

    /** null. */
    private String displayName;

    /** null. */
    private String password;

    /** null. */
    private Integer status;

    /** null. */
    private String ref;

    /** null. */
    private String scopeId;

    /** null. */
    private String email;

    /** null. */
    private String mobile;

    public CommonEntity() {
    }

    public CommonEntity(String username, String displayName,
            String password, Integer status, String ref, String scopeId,
            String email, String mobile) {
        this.username = username;
        this.displayName = displayName;
        this.password = password;
        this.status = status;
        this.ref = ref;
        this.scopeId = scopeId;
        this.email = email;
        this.mobile = mobile;
    }

    /** @return null. */
    @Id
    @GeneratedValue
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            null.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return null. */
    @Column(name = "USERNAME", length = 50)
    public String getUsername() {
        return this.username;
    }

    /**
     * @param username
     *            null.
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /** @return null. */
    @Column(name = "DISPLAY_NAME", length = 50)
    public String getDisplayName() {
        return this.displayName;
    }

    /**
     * @param displayName
     *            null.
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    /** @return null. */
    @Column(name = "PASSWORD", length = 50)
    public String getPassword() {
        return this.password;
    }

    /**
     * @param password
     *            null.
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /** @return null. */
    @Column(name = "STATUS")
    public Integer getStatus() {
        return this.status;
    }

    /**
     * @param status
     *            null.
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /** @return null. */
    @Column(name = "REF", length = 200)
    public String getRef() {
        return this.ref;
    }

    /**
     * @param ref
     *            null.
     */
    public void setRef(String ref) {
        this.ref = ref;
    }

    /** @return null. */
    @Column(name = "SCOPE_ID", length = 50)
    public String getScopeId() {
        return this.scopeId;
    }

    /**
     * @param scopeId
     *            null.
     */
    public void setScopeId(String scopeId) {
        this.scopeId = scopeId;
    }

    /** @return null. */
    @Column(name = "EMAIL", length = 100)
    public String getEmail() {
        return this.email;
    }

    /**
     * @param email
     *            null.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /** @return null. */
    @Column(name = "MOBILE", length = 50)
    public String getMobile() {
        return this.mobile;
    }

    /**
     * @param mobile
     *            null.
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
}
